import { localized } from '../../../shared/i18n/localized';
import {
  ManagementTab,
  Permission,
  PromotionIcon,
  PromotionStatus,
  ServiceCategory,
  UserFilter,
} from '../models/management';

// Textos de la pantalla de gestión en los 4 idiomas de la app
const es = {
  online: 'Sistema en línea · Sucursal Central',

  tabs: {
    users: 'Usuarios',
    roles: 'Roles',
    services: 'Servicios',
    promotions: 'Promociones',
  } as Record<ManagementTab, string>,

  common: {
    cancel: 'Cancelar',
    delete: 'Eliminar',
    yes: 'Sí',
    no: 'No',
    saveError: 'No se pudo guardar',
  },

  // ---------------- Usuarios ----------------
  users: {
    title: 'Gestión',
    subtitle: 'Supervisa los accesos del personal, roles asignados y estados de cuenta.',
    create: 'Crear usuario',
    search: 'Buscar por nombre, correo o rol...',
    filters: {
      enabled: 'Habilitados',
      registered: 'Registrados',
      disabled: 'Inhabilitados',
    } as Record<UserFilter, string>,
    empty: 'No se encontraron usuarios',
    emptyHint: 'Prueba cambiando la búsqueda o el filtro',
    noRole: 'Sin rol',
    // la base todavía no guarda la fecha de registro: se muestra el último ingreso
    createdAt: 'Último ingreso',
    loading: 'Cargando usuarios...',
    loadError: 'No se pudieron cargar los usuarios',
    retry: 'Reintentar',
    statusError: 'No se pudo cambiar el estado',
    disableTitle: 'Desactivar cuenta',
    disableMessage: (name: string) =>
      `${name} ya no podrá iniciar sesión y se cerrarán sus sesiones abiertas. Sus reservas y pagos se conservan.`,
    enableTitle: 'Activar cuenta',
    enableMessage: (name: string) => `${name} podrá volver a iniciar sesión.`,
    confirm: 'Aceptar',
    invited: 'Invitado',
    active: 'Activo',
    inactive: 'Inactivo',
    deleteTitle: 'Eliminar usuario',
    deleteMessage: (name: string) =>
      `¿Seguro que quieres eliminar a ${name}? Esta acción no se puede deshacer.`,
    form: {
      createTitle: 'Crear Usuario',
      createSubtitle: 'La persona iniciará sesión con este correo y la contraseña temporal. Podrá cambiarla en su perfil.',
      editTitle: 'Editar Usuario',
      editSubtitle: 'Actualiza los datos y el rol de la persona',
      name: 'Nombre completo',
      firstName: 'Nombres',
      lastName: 'Apellidos',
      document: 'Número de documento',
      phone: 'Teléfono',
      password: 'Contraseña temporal',
      showPassword: 'Mostrar contraseña',
      creating: 'Creando cuenta...',
      createdTitle: 'Cuenta creada',
      createdMessage: (name: string) => `${name} ya puede iniciar sesión con su correo y la contraseña temporal.`,
      namePlaceholder: 'Ej. María Fernanda López',
      email: 'Correo electrónico',
      emailPlaceholder: 'correo@ejemplo.com',
      role: 'Rol asignado',
      invite: 'Enviar invitación por correo',
      create: 'Crear Usuario',
      save: 'Guardar cambios',
      errors: {
        name: 'Ingresa los nombres',
        lastName: 'Ingresa los apellidos',
        document: 'Debe tener entre 5 y 20 dígitos',
        password: 'Mínimo 8 caracteres, una mayúscula, un número y un carácter especial',
        email: 'El correo no es válido',
        emailTaken: 'Este correo ya está registrado',
        role: 'Selecciona un rol',
      },
    },
  },

  // ---------------- Roles ----------------
  roles: {
    title: 'Roles',
    subtitle: 'Los 3 roles son fijos: elige uno y asígnale sus permisos.',
    users: (total: number) => (total === 1 ? '1 usuario' : `${total} usuarios`),
    empty: 'No hay permisos configurados',
    emptyHint: 'Edita un rol para asignarle permisos',
    noPermissions: 'Sin permisos',
    retryHint: 'Toca para intentar de nuevo',
    // se deja como fallback de visualización; el catálogo real viene de security-service
    permissions: {
      view_panels: 'Ver paneles',
      create_records: 'Crear registros',
      edit_data: 'Editar datos',
      delete: 'Eliminar',
    } as Record<Permission, string>,
    form: {
      editTitle: 'Permisos del rol',
      editSubtitle: 'Los 3 roles son fijos: elige uno y marca sus permisos.',
      roleSelectLabel: 'Rol',
      permissions: 'Permisos habilitados',
      save: 'Guardar cambios',
    },
  },

  // ---------------- Servicios ----------------
  services: {
    title: 'Servicios',
    subtitle: 'Administra el catálogo de servicios que se ofrecen a los clientes.',
    create: 'Agregar servicio',
    active: 'Activo',
    inactive: 'Inactivo',
    duration: (minutes: number) => `${minutes} min`,
    empty: 'No hay servicios en el catálogo',
    emptyHint: 'Agrega el primero con el botón de arriba',
    categories: {
      wash: 'Lavado',
      shine: 'Brillado',
      detail: 'Detallado',
      interior: 'Interior',
    } as Record<ServiceCategory, string>,
    deleteTitle: 'Eliminar servicio',
    deleteMessage: (name: string) =>
      `¿Seguro que quieres eliminar el servicio ${name}? Esta acción no se puede deshacer.`,
    form: {
      createTitle: 'Agregar Nuevo Servicio',
      createSubtitle: 'Configura tarifa y tiempo para asignación de bahía',
      editTitle: 'Editar Servicio',
      editSubtitle: 'Actualiza la tarifa y el tiempo del servicio',
      name: 'Nombre del Servicio',
      namePlaceholder: 'Ej. Desinfección con Ozono',
      price: 'Precio (COP)',
      pricePlaceholder: '45.000',
      description: 'Descripción',
      descriptionPlaceholder: 'Describe los detalles del servicio...',
      duration: 'Duración estimada',
      category: 'Categoría',
      create: 'Guardar Servicio',
      save: 'Guardar cambios',
    },
  },

  // ---------------- Promociones ----------------
  promotions: {
    title: 'Promociones',
    subtitle: 'Administra los paquetes promocionales y cupones de descuento.',
    create: 'Crear promoción',
    coupon: 'Cupón',
    redemptions: (total: number) => `${total} canjes`,
    featured: 'Destacada',
    duration: (minutes: number) => `${minutes} min`,
    editCard: 'Editar tarjeta',
    empty: 'No hay promociones creadas',
    emptyHint: 'Crea la primera con el botón de arriba',
    status: {
      active: 'Activa',
      paused: 'Pausada',
      scheduled: 'Programada',
    } as Record<PromotionStatus, string>,
    action: {
      active: 'Pausar',
      paused: 'Reanudar',
      scheduled: 'Comenzar ahora',
    } as Record<PromotionStatus, string>,
    icons: {
      'directions-car': 'Auto',
      'water-drop': 'Gota',
      'auto-awesome': 'Brillo',
    } as Record<PromotionIcon, string>,
    metrics: {
      redemptions: 'Total canjes',
      savings: 'Ahorro a clientes',
      conversion: 'Conversión de cupones',
    },
    deleteTitle: 'Eliminar promoción',
    deleteMessage: (name: string) =>
      `¿Seguro que quieres eliminar la promoción ${name}? Esta acción no se puede deshacer.`,
    form: {
      createTitle: 'Nueva promoción',
      createSubtitle: 'Crea una oferta para atraer más clientes al lavadero.',
      editTitle: 'Editar promoción',
      editSubtitle: 'Actualiza los datos de la oferta.',
      name: 'Nombre',
      namePlaceholder: 'Ej. Lavado premium 2x1',
      coupon: 'Cupón',
      couponPlaceholder: 'Ej. PREMIUM20',
      description: 'Descripción',
      descriptionPlaceholder: 'Escribe los beneficios de la promoción',
      price: 'Precio promocional',
      duration: 'Duración (min)',
      icon: 'Icono',
      status: 'Estado',
      startDate: 'Fecha de inicio',
      featured: 'Destacar en la app',
      benefits: 'Beneficios',
      addBenefit: 'Agregar beneficio',
      noBenefits: 'Aún no hay beneficios.',
      benefitPlaceholder: 'Describe el beneficio',
      discountPercent: 'Descuento al canjear (%)',
      requiredPoints: 'Puntos de fidelización necesarios',
      save: 'Guardar',
      errors: {
        name: 'Ingresa el nombre',
        coupon: 'Ingresa un cupón (mínimo 4 caracteres)',
        description: 'Escribe la descripción',
        price: 'Ingresa un precio válido',
        duration: 'Duración inválida',
        startDate: 'Fecha inválida (dd/mm/aaaa)',
        discountPercent: 'Ingresa un descuento entre 1 y 100',
      },
    },
  },
};

const en: typeof es = {
  online: 'System online · Main branch',
  tabs: { users: 'Users', roles: 'Roles', services: 'Services', promotions: 'Promotions' },
  common: { cancel: 'Cancel', delete: 'Delete', yes: 'Yes', no: 'No', saveError: "Couldn't save changes" },
  users: {
    title: 'Management',
    subtitle: 'Oversee staff access, assigned roles and account status.',
    create: 'Create user',
    search: 'Search by name, email or role...',
    filters: { enabled: 'Enabled', registered: 'Registered', disabled: 'Disabled' },
    empty: 'No users found',
    emptyHint: 'Try changing the search or the filter',
    noRole: 'No role',
    createdAt: 'Last sign-in',
    loading: 'Loading users...',
    loadError: 'Users could not be loaded',
    retry: 'Retry',
    statusError: 'The status could not be changed',
    disableTitle: 'Deactivate account',
    disableMessage: (name: string) =>
      `${name} will no longer be able to sign in and their open sessions will be closed. Their bookings and payments are kept.`,
    enableTitle: 'Activate account',
    enableMessage: (name: string) => `${name} will be able to sign in again.`,
    confirm: 'Accept',
    invited: 'Invited',
    active: 'Active',
    inactive: 'Inactive',
    deleteTitle: 'Delete user',
    deleteMessage: (name: string) => `Are you sure you want to delete ${name}? This action cannot be undone.`,
    form: {
      createTitle: 'Create User',
      createSubtitle: 'The person will sign in with this email and the temporary password. They can change it in their profile.',
      editTitle: 'Edit User',
      editSubtitle: "Update the person's data and role",
      name: 'Full name',
      firstName: 'First names',
      lastName: 'Last names',
      document: 'Document number',
      phone: 'Phone',
      password: 'Temporary password',
      showPassword: 'Show password',
      creating: 'Creating account...',
      createdTitle: 'Account created',
      createdMessage: (name: string) => `${name} can now sign in with their email and the temporary password.`,
      namePlaceholder: 'E.g. María Fernanda López',
      email: 'Email',
      emailPlaceholder: 'email@example.com',
      role: 'Assigned role',
      invite: 'Send invitation by email',
      create: 'Create User',
      save: 'Save changes',
      errors: {
        name: 'Enter the first names',
        lastName: 'Enter the last names',
        document: 'Must have between 5 and 20 digits',
        password: 'At least 8 characters, one uppercase letter, one number and one special character',
        email: 'The email is not valid',
        emailTaken: 'This email is already registered',
        role: 'Select a role',
      },
    },
  },
  roles: {
    title: 'Roles',
    subtitle: 'The 3 roles are fixed: pick one and assign its permissions.',
    users: (total: number) => (total === 1 ? '1 user' : `${total} users`),
    empty: 'No permissions configured',
    emptyHint: 'Edit a role to assign it permissions',
    noPermissions: 'No permissions',
    retryHint: 'Tap to try again',
    permissions: { view_panels: 'View panels', create_records: 'Create records', edit_data: 'Edit data', delete: 'Delete' },
    form: {
      editTitle: 'Role permissions',
      editSubtitle: 'The 3 roles are fixed: pick one and check its permissions.',
      roleSelectLabel: 'Role',
      permissions: 'Enabled permissions',
      save: 'Save changes',
    },
  },
  services: {
    title: 'Services',
    subtitle: 'Manage the catalog of services offered to customers.',
    create: 'Add service',
    active: 'Active',
    inactive: 'Inactive',
    duration: (minutes: number) => `${minutes} min`,
    empty: 'No services in the catalog',
    emptyHint: 'Add the first one with the button above',
    categories: { wash: 'Wash', shine: 'Shine', detail: 'Detailing', interior: 'Interior' },
    deleteTitle: 'Delete service',
    deleteMessage: (name: string) => `Are you sure you want to delete the service ${name}? This action cannot be undone.`,
    form: {
      createTitle: 'Add New Service',
      createSubtitle: 'Set the price and time for bay assignment',
      editTitle: 'Edit Service',
      editSubtitle: 'Update the price and time of the service',
      name: 'Service name',
      namePlaceholder: 'E.g. Ozone disinfection',
      price: 'Price (COP)',
      pricePlaceholder: '45,000',
      description: 'Description',
      descriptionPlaceholder: 'Describe the service details...',
      duration: 'Estimated duration',
      category: 'Category',
      create: 'Save Service',
      save: 'Save changes',
    },
  },
  promotions: {
    title: 'Promotions',
    subtitle: 'Manage promotional packages and discount coupons.',
    create: 'Create promotion',
    coupon: 'Coupon',
    redemptions: (total: number) => `${total} redemptions`,
    featured: 'Featured',
    duration: (minutes: number) => `${minutes} min`,
    editCard: 'Edit card',
    empty: 'No promotions created',
    emptyHint: 'Create the first one with the button above',
    status: { active: 'Active', paused: 'Paused', scheduled: 'Scheduled' },
    action: { active: 'Pause', paused: 'Resume', scheduled: 'Start now' },
    icons: { 'directions-car': 'Car', 'water-drop': 'Drop', 'auto-awesome': 'Shine' },
    metrics: { redemptions: 'Total redemptions', savings: 'Customer savings', conversion: 'Coupon conversion' },
    deleteTitle: 'Delete promotion',
    deleteMessage: (name: string) => `Are you sure you want to delete the promotion ${name}? This action cannot be undone.`,
    form: {
      createTitle: 'New promotion',
      createSubtitle: 'Create an offer to attract more customers to the car wash.',
      editTitle: 'Edit promotion',
      editSubtitle: 'Update the offer data.',
      name: 'Name',
      namePlaceholder: 'E.g. Premium wash 2x1',
      coupon: 'Coupon',
      couponPlaceholder: 'E.g. PREMIUM20',
      description: 'Description',
      descriptionPlaceholder: 'Write the promotion benefits',
      price: 'Promotional price',
      duration: 'Duration (min)',
      icon: 'Icon',
      status: 'Status',
      startDate: 'Start date',
      featured: 'Feature in the app',
      benefits: 'Benefits',
      addBenefit: 'Add benefit',
      noBenefits: 'No benefits yet.',
      benefitPlaceholder: 'Describe the benefit',
      discountPercent: 'Discount on redemption (%)',
      requiredPoints: 'Loyalty points required',
      save: 'Save',
      errors: {
        name: 'Enter the name',
        coupon: 'Enter a coupon (at least 4 characters)',
        description: 'Write the description',
        price: 'Enter a valid price',
        duration: 'Invalid duration',
        startDate: 'Invalid date (dd/mm/yyyy)',
        discountPercent: 'Enter a discount between 1 and 100',
      },
    },
  },
};

const fr: typeof es = {
  online: 'Système en ligne · Agence centrale',
  tabs: { users: 'Utilisateurs', roles: 'Rôles', services: 'Services', promotions: 'Promotions' },
  common: { cancel: 'Annuler', delete: 'Supprimer', yes: 'Oui', no: 'Non', saveError: "Impossible d'enregistrer" },
  users: {
    title: 'Gestion',
    subtitle: 'Supervisez les accès du personnel, les rôles assignés et le statut des comptes.',
    create: 'Créer un utilisateur',
    search: 'Rechercher par nom, e-mail ou rôle...',
    filters: { enabled: 'Activés', registered: 'Inscrits', disabled: 'Désactivés' },
    empty: 'Aucun utilisateur trouvé',
    emptyHint: 'Essayez de modifier la recherche ou le filtre',
    noRole: 'Sans rôle',
    createdAt: 'Dernière connexion',
    loading: 'Chargement des utilisateurs...',
    loadError: 'Impossible de charger les utilisateurs',
    retry: 'Réessayer',
    statusError: 'Impossible de changer le statut',
    disableTitle: 'Désactiver le compte',
    disableMessage: (name: string) =>
      `${name} ne pourra plus se connecter et ses sessions ouvertes seront fermées. Ses réservations et paiements sont conservés.`,
    enableTitle: 'Activer le compte',
    enableMessage: (name: string) => `${name} pourra de nouveau se connecter.`,
    confirm: 'Accepter',
    invited: 'Invité',
    active: 'Actif',
    inactive: 'Inactif',
    deleteTitle: "Supprimer l'utilisateur",
    deleteMessage: (name: string) => `Voulez-vous vraiment supprimer ${name} ? Cette action est irréversible.`,
    form: {
      createTitle: 'Créer un utilisateur',
      createSubtitle: 'La personne se connectera avec cet e-mail et le mot de passe temporaire. Elle pourra le changer dans son profil.',
      editTitle: "Modifier l'utilisateur",
      editSubtitle: 'Mettez à jour les données et le rôle de la personne',
      name: 'Nom complet',
      firstName: 'Prénoms',
      lastName: 'Noms',
      document: 'Numéro de document',
      phone: 'Téléphone',
      password: 'Mot de passe temporaire',
      showPassword: 'Afficher le mot de passe',
      creating: 'Création du compte...',
      createdTitle: 'Compte créé',
      createdMessage: (name: string) => `${name} peut désormais se connecter avec son e-mail et le mot de passe temporaire.`,
      namePlaceholder: 'Ex. María Fernanda López',
      email: 'E-mail',
      emailPlaceholder: 'email@exemple.com',
      role: 'Rôle assigné',
      invite: 'Envoyer une invitation par e-mail',
      create: 'Créer un utilisateur',
      save: 'Enregistrer',
      errors: {
        name: 'Saisissez les prénoms',
        lastName: 'Saisissez les noms',
        document: 'Doit contenir entre 5 et 20 chiffres',
        password: '8 caractères minimum, une majuscule, un chiffre et un caractère spécial',
        email: "L'e-mail n'est pas valide",
        emailTaken: 'Cet e-mail est déjà enregistré',
        role: 'Sélectionnez un rôle',
      },
    },
  },
  roles: {
    title: 'Rôles',
    subtitle: 'Les 3 rôles sont fixes : choisissez-en un et attribuez-lui ses permissions.',
    users: (total: number) => (total === 1 ? '1 utilisateur' : `${total} utilisateurs`),
    empty: 'Aucune permission configurée',
    emptyHint: 'Modifiez un rôle pour lui attribuer des permissions',
    noPermissions: 'Aucune permission',
    retryHint: 'Touchez pour réessayer',
    permissions: { view_panels: 'Voir les panneaux', create_records: 'Créer des registres', edit_data: 'Modifier les données', delete: 'Supprimer' },
    form: {
      editTitle: 'Permissions du rôle',
      editSubtitle: 'Les 3 rôles sont fixes : choisissez-en un et cochez ses permissions.',
      roleSelectLabel: 'Rôle',
      permissions: 'Permissions activées',
      save: 'Enregistrer',
    },
  },
  services: {
    title: 'Services',
    subtitle: 'Gérez le catalogue des services proposés aux clients.',
    create: 'Ajouter un service',
    active: 'Actif',
    inactive: 'Inactif',
    duration: (minutes: number) => `${minutes} min`,
    empty: 'Aucun service dans le catalogue',
    emptyHint: 'Ajoutez le premier avec le bouton ci-dessus',
    categories: { wash: 'Lavage', shine: 'Lustrage', detail: 'Détaillage', interior: 'Intérieur' },
    deleteTitle: 'Supprimer le service',
    deleteMessage: (name: string) => `Voulez-vous vraiment supprimer le service ${name} ? Cette action est irréversible.`,
    form: {
      createTitle: 'Ajouter un nouveau service',
      createSubtitle: "Configurez le tarif et la durée pour l'attribution de baie",
      editTitle: 'Modifier le service',
      editSubtitle: 'Mettez à jour le tarif et la durée du service',
      name: 'Nom du service',
      namePlaceholder: "Ex. Désinfection à l'ozone",
      price: 'Prix (COP)',
      pricePlaceholder: '45 000',
      description: 'Description',
      descriptionPlaceholder: 'Décrivez les détails du service...',
      duration: 'Durée estimée',
      category: 'Catégorie',
      create: 'Enregistrer le service',
      save: 'Enregistrer',
    },
  },
  promotions: {
    title: 'Promotions',
    subtitle: 'Gérez les offres promotionnelles et les coupons de réduction.',
    create: 'Créer une promotion',
    coupon: 'Coupon',
    redemptions: (total: number) => `${total} utilisations`,
    featured: 'En vedette',
    duration: (minutes: number) => `${minutes} min`,
    editCard: 'Modifier la carte',
    empty: 'Aucune promotion créée',
    emptyHint: 'Créez la première avec le bouton ci-dessus',
    status: { active: 'Active', paused: 'En pause', scheduled: 'Programmée' },
    action: { active: 'Mettre en pause', paused: 'Reprendre', scheduled: 'Commencer maintenant' },
    icons: { 'directions-car': 'Voiture', 'water-drop': 'Goutte', 'auto-awesome': 'Brillance' },
    metrics: { redemptions: 'Utilisations totales', savings: 'Économies clients', conversion: 'Conversion des coupons' },
    deleteTitle: 'Supprimer la promotion',
    deleteMessage: (name: string) => `Voulez-vous vraiment supprimer la promotion ${name} ? Cette action est irréversible.`,
    form: {
      createTitle: 'Nouvelle promotion',
      createSubtitle: 'Créez une offre pour attirer plus de clients au lavage.',
      editTitle: 'Modifier la promotion',
      editSubtitle: "Mettez à jour les données de l'offre.",
      name: 'Nom',
      namePlaceholder: 'Ex. Lavage premium 2x1',
      coupon: 'Coupon',
      couponPlaceholder: 'Ex. PREMIUM20',
      description: 'Description',
      descriptionPlaceholder: 'Écrivez les avantages de la promotion',
      price: 'Prix promotionnel',
      duration: 'Durée (min)',
      icon: 'Icône',
      status: 'Statut',
      startDate: 'Date de début',
      featured: "Mettre en avant dans l'application",
      benefits: 'Avantages',
      addBenefit: 'Ajouter un avantage',
      noBenefits: "Pas encore d'avantages.",
      benefitPlaceholder: "Décrivez l'avantage",
      discountPercent: "Remise à l'échange (%)",
      requiredPoints: 'Points de fidélité requis',
      save: 'Enregistrer',
      errors: {
        name: 'Saisissez le nom',
        coupon: 'Saisissez un coupon (4 caractères minimum)',
        description: 'Écrivez la description',
        price: 'Saisissez un prix valide',
        duration: 'Durée invalide',
        startDate: 'Date invalide (jj/mm/aaaa)',
        discountPercent: 'Saisissez une remise entre 1 et 100',
      },
    },
  },
};

const pt: typeof es = {
  online: 'Sistema on-line · Filial Central',
  tabs: { users: 'Usuários', roles: 'Funções', services: 'Serviços', promotions: 'Promoções' },
  common: { cancel: 'Cancelar', delete: 'Excluir', yes: 'Sim', no: 'Não', saveError: 'Não foi possível salvar' },
  users: {
    title: 'Gestão',
    subtitle: 'Supervisione os acessos da equipe, as funções atribuídas e o status das contas.',
    create: 'Criar usuário',
    search: 'Buscar por nome, e-mail ou função...',
    filters: { enabled: 'Habilitados', registered: 'Cadastrados', disabled: 'Desabilitados' },
    empty: 'Nenhum usuário encontrado',
    emptyHint: 'Tente mudar a busca ou o filtro',
    noRole: 'Sem função',
    createdAt: 'Último acesso',
    loading: 'Carregando usuários...',
    loadError: 'Não foi possível carregar os usuários',
    retry: 'Tentar novamente',
    statusError: 'Não foi possível mudar o status',
    disableTitle: 'Desativar conta',
    disableMessage: (name: string) =>
      `${name} não poderá mais entrar e suas sessões abertas serão encerradas. Suas reservas e pagamentos são mantidos.`,
    enableTitle: 'Ativar conta',
    enableMessage: (name: string) => `${name} poderá entrar novamente.`,
    confirm: 'Aceitar',
    invited: 'Convidado',
    active: 'Ativo',
    inactive: 'Inativo',
    deleteTitle: 'Excluir usuário',
    deleteMessage: (name: string) => `Tem certeza de que deseja excluir ${name}? Esta ação não pode ser desfeita.`,
    form: {
      createTitle: 'Criar Usuário',
      createSubtitle: 'A pessoa entrará com este e-mail e a senha temporária. Poderá alterá-la no perfil.',
      editTitle: 'Editar Usuário',
      editSubtitle: 'Atualize os dados e a função da pessoa',
      name: 'Nome completo',
      firstName: 'Nomes',
      lastName: 'Sobrenomes',
      document: 'Número do documento',
      phone: 'Telefone',
      password: 'Senha temporária',
      showPassword: 'Mostrar senha',
      creating: 'Criando conta...',
      createdTitle: 'Conta criada',
      createdMessage: (name: string) => `${name} já pode entrar com seu e-mail e a senha temporária.`,
      namePlaceholder: 'Ex. María Fernanda López',
      email: 'E-mail',
      emailPlaceholder: 'email@exemplo.com',
      role: 'Função atribuída',
      invite: 'Enviar convite por e-mail',
      create: 'Criar Usuário',
      save: 'Salvar alterações',
      errors: {
        name: 'Informe os nomes',
        lastName: 'Informe os sobrenomes',
        document: 'Deve ter entre 5 e 20 dígitos',
        password: 'Mínimo 8 caracteres, uma maiúscula, um número e um caractere especial',
        email: 'O e-mail não é válido',
        emailTaken: 'Este e-mail já está cadastrado',
        role: 'Selecione uma função',
      },
    },
  },
  roles: {
    title: 'Funções',
    subtitle: 'As 3 funções são fixas: escolha uma e atribua suas permissões.',
    users: (total: number) => (total === 1 ? '1 usuário' : `${total} usuários`),
    empty: 'Nenhuma permissão configurada',
    emptyHint: 'Edite uma função para atribuir permissões',
    noPermissions: 'Sem permissões',
    retryHint: 'Toque para tentar novamente',
    permissions: { view_panels: 'Ver painéis', create_records: 'Criar registros', edit_data: 'Editar dados', delete: 'Excluir' },
    form: {
      editTitle: 'Permissões da função',
      editSubtitle: 'As 3 funções são fixas: escolha uma e marque suas permissões.',
      roleSelectLabel: 'Função',
      permissions: 'Permissões habilitadas',
      save: 'Salvar alterações',
    },
  },
  services: {
    title: 'Serviços',
    subtitle: 'Gerencie o catálogo de serviços oferecidos aos clientes.',
    create: 'Adicionar serviço',
    active: 'Ativo',
    inactive: 'Inativo',
    duration: (minutes: number) => `${minutes} min`,
    empty: 'Não há serviços no catálogo',
    emptyHint: 'Adicione o primeiro com o botão acima',
    categories: { wash: 'Lavagem', shine: 'Polimento', detail: 'Detalhamento', interior: 'Interior' },
    deleteTitle: 'Excluir serviço',
    deleteMessage: (name: string) => `Tem certeza de que deseja excluir o serviço ${name}? Esta ação não pode ser desfeita.`,
    form: {
      createTitle: 'Adicionar Novo Serviço',
      createSubtitle: 'Configure a tarifa e o tempo para a atribuição da baia',
      editTitle: 'Editar Serviço',
      editSubtitle: 'Atualize a tarifa e o tempo do serviço',
      name: 'Nome do serviço',
      namePlaceholder: 'Ex. Desinfecção com ozônio',
      price: 'Preço (COP)',
      pricePlaceholder: '45.000',
      description: 'Descrição',
      descriptionPlaceholder: 'Descreva os detalhes do serviço...',
      duration: 'Duração estimada',
      category: 'Categoria',
      create: 'Salvar Serviço',
      save: 'Salvar alterações',
    },
  },
  promotions: {
    title: 'Promoções',
    subtitle: 'Gerencie os pacotes promocionais e cupons de desconto.',
    create: 'Criar promoção',
    coupon: 'Cupom',
    redemptions: (total: number) => `${total} resgates`,
    featured: 'Destaque',
    duration: (minutes: number) => `${minutes} min`,
    editCard: 'Editar cartão',
    empty: 'Não há promoções criadas',
    emptyHint: 'Crie a primeira com o botão acima',
    status: { active: 'Ativa', paused: 'Pausada', scheduled: 'Programada' },
    action: { active: 'Pausar', paused: 'Retomar', scheduled: 'Começar agora' },
    icons: { 'directions-car': 'Carro', 'water-drop': 'Gota', 'auto-awesome': 'Brilho' },
    metrics: { redemptions: 'Total de resgates', savings: 'Economia dos clientes', conversion: 'Conversão de cupons' },
    deleteTitle: 'Excluir promoção',
    deleteMessage: (name: string) => `Tem certeza de que deseja excluir a promoção ${name}? Esta ação não pode ser desfeita.`,
    form: {
      createTitle: 'Nova promoção',
      createSubtitle: 'Crie uma oferta para atrair mais clientes ao lava-rápido.',
      editTitle: 'Editar promoção',
      editSubtitle: 'Atualize os dados da oferta.',
      name: 'Nome',
      namePlaceholder: 'Ex. Lavagem premium 2x1',
      coupon: 'Cupom',
      couponPlaceholder: 'Ex. PREMIUM20',
      description: 'Descrição',
      descriptionPlaceholder: 'Escreva os benefícios da promoção',
      price: 'Preço promocional',
      duration: 'Duração (min)',
      icon: 'Ícone',
      status: 'Status',
      startDate: 'Data de início',
      featured: 'Destacar no app',
      benefits: 'Benefícios',
      addBenefit: 'Adicionar benefício',
      noBenefits: 'Ainda não há benefícios.',
      benefitPlaceholder: 'Descreva o benefício',
      discountPercent: 'Desconto ao resgatar (%)',
      requiredPoints: 'Pontos de fidelidade necessários',
      save: 'Salvar',
      errors: {
        name: 'Informe o nome',
        coupon: 'Informe um cupom (mínimo 4 caracteres)',
        description: 'Escreva a descrição',
        price: 'Informe um preço válido',
        duration: 'Duração inválida',
        startDate: 'Data inválida (dd/mm/aaaa)',
        discountPercent: 'Informe um desconto entre 1 e 100',
      },
    },
  },
};

export const MANAGEMENT_TEXTS = localized({ es, en, fr, pt });
