import { localized } from '../../../shared/i18n/localized';
import {
  CalendarBlockType,
  CalendarView,
  OperatorFilter,
  OperatorStatus,
  ServiceStatus,
  SkillLevel,
} from '../models/operator';

// Textos de la pantalla de operarios en los 4 idiomas de la app
const es = {
  title: 'Operarios',
  subtitle: 'Gestiona el equipo técnico, sus turnos y su disponibilidad operativa en tiempo real',
  assignShifts: 'Asignar turnos',
  newOperator: 'Nuevo operario',
  inactiveTag: 'Inactivo',
  manageInUsers: 'Los operarios son cuentas con rol Operario: se crean y editan en Gestión → Usuarios.',

  common: { cancel: 'Cancelar' },

  // ---------------- Tarjetas de resumen ----------------
  summary: {
    staff: 'Operarios en plantilla',
    staffDetail: (hired: number, interns: number) => `${hired} contratados · ${interns} pasantes`,
    availableToday: 'Disponibles hoy',
    availableDetail: (total: number) => `${total} en turno tarde (14:00 - 22:00)`,
    weeklyServices: 'Servicios de la semana',
    trend: (percent: number) => `${percent >= 0 ? '+' : ''}${percent}% vs semana anterior`,
    rating: 'Calificación promedio',
    ratingBase: (total: number) => `Basado en ${total} reseñas de clientes`,
  },

  // ---------------- Filtros ----------------
  search: 'Buscar por nombre o especialidad...',
  filters: {
    all: 'Todos',
    available: 'Disponibles',
    in_service: 'En servicio',
    absent: 'Ausentes',
  } as Record<OperatorFilter, string>,
  empty: 'No se encontraron operarios',
  emptyHint: 'Prueba cambiando la búsqueda o el filtro',

  status: {
    available: 'Disponible',
    in_service: 'En servicio',
    absent: 'Permiso médico',
  } as Record<OperatorStatus, string>,

  // ---------------- Tarjeta de operario ----------------
  card: {
    rating: 'Calificación clientes',
    noRating: 'Sin calificaciones',
    bay: 'Bahía asignada',
    noBay: 'Sin asignar',
    services: (total: number) => `${total} ${total === 1 ? 'servicio' : 'servicios'}`,
    servicesAbsent: (total: number, reason: string) =>
      `${total} ${total === 1 ? 'servicio' : 'servicios'} (${reason})`,
    viewAvailability: 'Ver disponibilidad',
    registerReturn: 'Registrar reingreso',
  },

  // ---------------- Detalle ----------------
  detail: {
    back: 'Volver a Operarios',
    title: (name: string) => `Disponibilidad de ${name}`,
    idLabel: (code: string) => `ID: ${code}`,
    ratingLine: (rating: string, reviews: number) => `${rating} (${reviews} valoraciones)`,
    bayLine: (bay: string) => `Bahía asignada: ${bay}`,
    registerAbsence: 'Registrar ausencia',
    registerReturn: 'Registrar reingreso',
    editAvailability: 'Editar disponibilidad',
    assignBay: 'Asignar bahía / turno',
    absentUntil: (date: string) => `Ausente hasta el ${date}`,
  },

  metrics: {
    services: 'Servicios de la semana',
    servicesUnit: 'servicios',
    hours: 'Horas disponibles',
    hoursOf: (capacity: number) => `/ ${capacity} hrs`,
    occupied: (percent: number) => `${percent}% del cupo operativo ocupado`,
    punctuality: 'Puntualidad',
    punctualityNote: 'Excelente registro de turnos',
    revenue: 'Ingresos generados semana',
    goal: (percent: number) => `${percent}% de meta semanal cumplida`,
  },

  today: {
    title: 'Historial de servicios de hoy',
    assigned: (total: number) => `${total} ${total === 1 ? 'servicio asignado' : 'servicios asignados'}`,
    subtitle: (bay: string) => `Gestión de flujo de trabajo en tiempo real para ${bay}`,
    subtitleNoBay: 'Gestión de flujo de trabajo en tiempo real',
    empty: 'Sin servicios asignados hoy',
    bay: 'Bahía',
    status: {
      completed: 'Completado',
      in_progress: 'En proceso',
      scheduled: 'Agendado',
    } as Record<ServiceStatus, string>,
    action: {
      completed: 'Detalles',
      in_progress: 'Bitácora',
      scheduled: 'Ver orden',
    } as Record<ServiceStatus, string>,
    close: 'Cerrar',
  },

  skills: {
    title: 'Habilidades y certificaciones',
    empty: 'Sin habilidades registradas',
    levels: {
      certified: 'Certificado',
      expert: 'Nivel Experto',
      advanced: 'Avanzado',
    } as Record<SkillLevel, string>,
    ruleTitle: 'Regla operativa de bahías',
    ruleText: (name: string, bay: string) =>
      `Los bloques de servicio asignados a ${name} no pueden solaparse con turnos de mantenimiento general en ${bay}.`,
    ruleTextNoBay: (name: string) =>
      `Los bloques de servicio asignados a ${name} no pueden solaparse con turnos de mantenimiento general.`,
    export: 'Exportar ficha técnica (PDF)',
  },

  // ---------------- Modales ----------------
  form: {
    createTitle: 'Nuevo operario',
    editTitle: 'Editar operario',
    subtitle: 'Registra los datos del operario y su bahía de trabajo.',
    name: 'Nombre completo',
    accountHint: 'Se creará la cuenta con la que el operario inicia sesión. Entrégale el correo y la contraseña temporal.',
    firstName: 'Nombres',
    lastName: 'Apellidos',
    document: 'Número de documento',
    password: 'Contraseña temporal',
    showPassword: 'Mostrar contraseña',
    creating: 'Creando cuenta...',
    namePlaceholder: 'Nombre y apellido',
    specialty: 'Especialidad',
    specialtyPlaceholder: 'Ej. Detallado cerámico',
    phone: 'Teléfono',
    phonePlaceholder: '+57 300 000 0000',
    email: 'Correo electrónico',
    emailPlaceholder: 'operario@lavadero.co',
    status: 'Estado',
    bay: 'Bahía',
    noBay: 'Sin bahía asignada',
    bayNotApplicable: 'No aplica: el operario está en permiso médico',
    tags: 'Etiquetas',
    addTag: 'Agregar etiqueta',
    noTags: 'Aún no hay etiquetas.',
    tagPlaceholder: 'Ej. Pulido cerámico',
    save: 'Guardar',
    errors: {
      name: 'Ingresa el nombre completo',
      firstName: 'Ingresa los nombres',
      lastName: 'Ingresa los apellidos',
      document: 'Debe tener entre 5 y 20 dígitos',
      password: 'Mínimo 8 caracteres, una mayúscula, un número y un carácter especial',
      specialty: 'Ingresa la especialidad',
      phone: 'Ingresa un teléfono válido',
      email: 'El correo no es válido',
    },
  },

  assign: {
    title: 'Asignar turno',
    subtitle: 'Elige el operario, su estado y la bahía del turno.',
    operator: 'Operario',
    status: 'Estado',
    bay: 'Bahía',
    noBay: 'Sin bahía asignada',
    hint: 'La bahía no se puede asignar cuando el operario está en incapacidad.',
    submit: 'Asignar turno',
  },

  availability: {
    title: 'Disponibilidad semanal',
    subtitle: 'Define los horarios en los que el operario atiende servicios.',
    hint: 'Desmarca el día para indicar que el operario no trabaja ese día.',
    start: 'Inicio',
    end: 'Fin',
    error: 'Usa el formato hh:mm y el inicio debe ser antes del fin',
    save: 'Guardar',
  },

  absence: {
    title: 'Registrar incapacidad',
    subtitle: 'Registra el período en que el operario no estará disponible.',
    start: 'Fecha de inicio',
    end: 'Fecha de fin',
    reason: 'Motivo',
    reasonPlaceholder: 'Ej. Incapacidad médica',
    save: 'Guardar',
    errors: {
      date: 'Fecha inválida (dd/mm/aaaa)',
      range: 'La fecha de fin no puede ser anterior al inicio',
    },
  },

  returnDialog: {
    title: 'Registrar reingreso',
    message: (name: string) =>
      `¿Confirmas que ${name} regresa a trabajar? Su estado pasará a Disponible.`,
    confirm: 'Confirmar',
  },

  // ---------------- Calendario del operario ----------------
  calendar: {
    open: 'Ver calendario de turnos',
    title: (name: string) => `Calendario de ${name}`,
    subtitle: 'Turnos, servicios y ausencias del operario',
    back: 'Volver a la ficha',
    weekLabel: (week: number, from: string, to: string) => `Semana ${week}: ${from} – ${to}`,
    fullDay: (from: string, to: string) => `Jornada completa: ${from} – ${to}`,
    views: { week: 'Semana', day: 'Día', month: 'Mes' } as Record<CalendarView, string>,
    legend: {
      available: 'Disponible',
      service: 'Servicio asignado',
      leave: 'Ausencia aprobada',
      lunch: 'Almuerzo / pausa',
    } as Record<CalendarBlockType, string>,
    today: 'Hoy',
    free: 'Disponible',
    lunch: 'Almuerzo',
    dayOff: 'No trabaja este día',
    blocks: (total: number) => (total === 1 ? '1 bloque' : `${total} bloques`),
  },
};

const en: typeof es = {
  title: 'Operators',
  subtitle: 'Manage the technical team, their shifts and operational availability in real time',
  assignShifts: 'Assign shifts',
  newOperator: 'New operator',
  inactiveTag: 'Inactive',
  manageInUsers: 'Operators are accounts with the Operator role: create and edit them in Management → Users.',
  common: { cancel: 'Cancel' },
  summary: {
    staff: 'Operators on staff',
    staffDetail: (hired: number, interns: number) => `${hired} hired · ${interns} interns`,
    availableToday: 'Available today',
    availableDetail: (total: number) => `${total} on the afternoon shift (14:00 - 22:00)`,
    weeklyServices: 'Services this week',
    trend: (percent: number) => `${percent >= 0 ? '+' : ''}${percent}% vs previous week`,
    rating: 'Average rating',
    ratingBase: (total: number) => `Based on ${total} customer reviews`,
  },
  search: 'Search by name or specialty...',
  filters: { all: 'All', available: 'Available', in_service: 'In service', absent: 'Absent' },
  empty: 'No operators found',
  emptyHint: 'Try changing the search or the filter',
  status: { available: 'Available', in_service: 'In service', absent: 'Medical leave' },
  card: {
    rating: 'Customer rating',
    noRating: 'No ratings',
    bay: 'Assigned bay',
    noBay: 'Unassigned',
    services: (total: number) => `${total} ${total === 1 ? 'service' : 'services'}`,
    servicesAbsent: (total: number, reason: string) => `${total} ${total === 1 ? 'service' : 'services'} (${reason})`,
    viewAvailability: 'View availability',
    registerReturn: 'Register return',
  },
  detail: {
    back: 'Back to Operators',
    title: (name: string) => `${name}'s availability`,
    idLabel: (code: string) => `ID: ${code}`,
    ratingLine: (rating: string, reviews: number) => `${rating} (${reviews} reviews)`,
    bayLine: (bay: string) => `Assigned bay: ${bay}`,
    registerAbsence: 'Register absence',
    registerReturn: 'Register return',
    editAvailability: 'Edit availability',
    assignBay: 'Assign bay / shift',
    absentUntil: (date: string) => `Absent until ${date}`,
  },
  metrics: {
    services: 'Services this week',
    servicesUnit: 'services',
    hours: 'Available hours',
    hoursOf: (capacity: number) => `/ ${capacity} hrs`,
    occupied: (percent: number) => `${percent}% of the operational capacity used`,
    punctuality: 'Punctuality',
    punctualityNote: 'Excellent shift record',
    revenue: 'Revenue generated this week',
    goal: (percent: number) => `${percent}% of the weekly goal reached`,
  },
  today: {
    title: "Today's service history",
    assigned: (total: number) => `${total} ${total === 1 ? 'service assigned' : 'services assigned'}`,
    subtitle: (bay: string) => `Real-time workflow management for ${bay}`,
    subtitleNoBay: 'Real-time workflow management',
    empty: 'No services assigned today',
    bay: 'Bay',
    status: { completed: 'Completed', in_progress: 'In progress', scheduled: 'Scheduled' },
    action: { completed: 'Details', in_progress: 'Log', scheduled: 'View order' },
    close: 'Close',
  },
  skills: {
    title: 'Skills and certifications',
    empty: 'No skills registered',
    levels: { certified: 'Certified', expert: 'Expert level', advanced: 'Advanced' },
    ruleTitle: 'Bay operating rule',
    ruleText: (name: string, bay: string) =>
      `Service blocks assigned to ${name} cannot overlap with general maintenance shifts in ${bay}.`,
    ruleTextNoBay: (name: string) => `Service blocks assigned to ${name} cannot overlap with general maintenance shifts.`,
    export: 'Export technical sheet (PDF)',
  },
  form: {
    createTitle: 'New operator',
    editTitle: 'Edit operator',
    subtitle: 'Register the operator data and their work bay.',
    name: 'Full name',
    accountHint: 'The account the operator signs in with will be created. Give them the email and the temporary password.',
    firstName: 'First names',
    lastName: 'Last names',
    document: 'Document number',
    password: 'Temporary password',
    showPassword: 'Show password',
    creating: 'Creating account...',
    namePlaceholder: 'First and last name',
    specialty: 'Specialty',
    specialtyPlaceholder: 'E.g. Ceramic detailing',
    phone: 'Phone',
    phonePlaceholder: '+57 300 000 0000',
    email: 'Email',
    emailPlaceholder: 'operator@carwash.co',
    status: 'Status',
    bay: 'Bay',
    noBay: 'No bay assigned',
    bayNotApplicable: 'Not applicable: the operator is on medical leave',
    tags: 'Tags',
    addTag: 'Add tag',
    noTags: 'No tags yet.',
    tagPlaceholder: 'E.g. Ceramic polishing',
    save: 'Save',
    errors: {
      name: 'Enter the full name',
      firstName: 'Enter the first names',
      lastName: 'Enter the last names',
      document: 'Must have between 5 and 20 digits',
      password: 'At least 8 characters, one uppercase letter, one number and one special character',
      specialty: 'Enter the specialty',
      phone: 'Enter a valid phone number',
      email: 'The email is not valid',
    },
  },
  assign: {
    title: 'Assign shift',
    subtitle: 'Choose the operator, their status and the shift bay.',
    operator: 'Operator',
    status: 'Status',
    bay: 'Bay',
    noBay: 'No bay assigned',
    hint: 'A bay cannot be assigned while the operator is on leave.',
    submit: 'Assign shift',
  },
  availability: {
    title: 'Weekly availability',
    subtitle: 'Set the hours when the operator handles services.',
    hint: 'Uncheck the day to indicate the operator does not work that day.',
    start: 'Start',
    end: 'End',
    error: 'Use the hh:mm format and the start must be before the end',
    save: 'Save',
  },
  absence: {
    title: 'Register leave',
    subtitle: 'Register the period when the operator will not be available.',
    start: 'Start date',
    end: 'End date',
    reason: 'Reason',
    reasonPlaceholder: 'E.g. Medical leave',
    save: 'Save',
    errors: { date: 'Invalid date (dd/mm/yyyy)', range: 'The end date cannot be before the start date' },
  },
  returnDialog: {
    title: 'Register return',
    message: (name: string) => `Do you confirm that ${name} is back to work? Their status will change to Available.`,
    confirm: 'Confirm',
  },
  calendar: {
    open: 'View shift calendar',
    title: (name: string) => `${name}'s calendar`,
    subtitle: "Operator's shifts, services and absences",
    back: 'Back to profile',
    weekLabel: (week: number, from: string, to: string) => `Week ${week}: ${from} – ${to}`,
    fullDay: (from: string, to: string) => `Full day: ${from} – ${to}`,
    views: { week: 'Week', day: 'Day', month: 'Month' },
    legend: { available: 'Available', service: 'Assigned service', leave: 'Approved absence', lunch: 'Lunch / break' },
    today: 'Today',
    free: 'Available',
    lunch: 'Lunch',
    dayOff: 'Does not work this day',
    blocks: (total: number) => (total === 1 ? '1 block' : `${total} blocks`),
  },
};

const fr: typeof es = {
  title: 'Opérateurs',
  subtitle: "Gérez l'équipe technique, ses horaires et sa disponibilité opérationnelle en temps réel",
  assignShifts: 'Assigner des horaires',
  newOperator: 'Nouvel opérateur',
  inactiveTag: 'Inactif',
  manageInUsers: 'Les opérateurs sont des comptes avec le rôle Opérateur : créez-les et modifiez-les dans Gestion → Utilisateurs.',
  common: { cancel: 'Annuler' },
  summary: {
    staff: "Opérateurs de l'effectif",
    staffDetail: (hired: number, interns: number) => `${hired} salariés · ${interns} stagiaires`,
    availableToday: "Disponibles aujourd'hui",
    availableDetail: (total: number) => `${total} en équipe d'après-midi (14:00 - 22:00)`,
    weeklyServices: 'Services de la semaine',
    trend: (percent: number) => `${percent >= 0 ? '+' : ''}${percent} % vs semaine précédente`,
    rating: 'Note moyenne',
    ratingBase: (total: number) => `Basée sur ${total} avis clients`,
  },
  search: 'Rechercher par nom ou spécialité...',
  filters: { all: 'Tous', available: 'Disponibles', in_service: 'En service', absent: 'Absents' },
  empty: 'Aucun opérateur trouvé',
  emptyHint: 'Essayez de modifier la recherche ou le filtre',
  status: { available: 'Disponible', in_service: 'En service', absent: 'Arrêt maladie' },
  card: {
    rating: 'Note clients',
    noRating: 'Aucune note',
    bay: 'Baie assignée',
    noBay: 'Non assignée',
    services: (total: number) => `${total} ${total === 1 ? 'service' : 'services'}`,
    servicesAbsent: (total: number, reason: string) => `${total} ${total === 1 ? 'service' : 'services'} (${reason})`,
    viewAvailability: 'Voir la disponibilité',
    registerReturn: 'Enregistrer le retour',
  },
  detail: {
    back: 'Retour aux opérateurs',
    title: (name: string) => `Disponibilité de ${name}`,
    idLabel: (code: string) => `ID : ${code}`,
    ratingLine: (rating: string, reviews: number) => `${rating} (${reviews} avis)`,
    bayLine: (bay: string) => `Baie assignée : ${bay}`,
    registerAbsence: 'Enregistrer une absence',
    registerReturn: 'Enregistrer le retour',
    editAvailability: 'Modifier la disponibilité',
    assignBay: 'Assigner baie / horaire',
    absentUntil: (date: string) => `Absent jusqu'au ${date}`,
  },
  metrics: {
    services: 'Services de la semaine',
    servicesUnit: 'services',
    hours: 'Heures disponibles',
    hoursOf: (capacity: number) => `/ ${capacity} h`,
    occupied: (percent: number) => `${percent} % de la capacité opérationnelle occupée`,
    punctuality: 'Ponctualité',
    punctualityNote: 'Excellent registre des horaires',
    revenue: 'Revenus générés cette semaine',
    goal: (percent: number) => `${percent} % de l'objectif hebdomadaire atteint`,
  },
  today: {
    title: "Historique des services d'aujourd'hui",
    assigned: (total: number) => `${total} ${total === 1 ? 'service assigné' : 'services assignés'}`,
    subtitle: (bay: string) => `Gestion du flux de travail en temps réel pour ${bay}`,
    subtitleNoBay: 'Gestion du flux de travail en temps réel',
    empty: "Aucun service assigné aujourd'hui",
    bay: 'Baie',
    status: { completed: 'Terminé', in_progress: 'En cours', scheduled: 'Programmé' },
    action: { completed: 'Détails', in_progress: 'Journal', scheduled: "Voir l'ordre" },
    close: 'Fermer',
  },
  skills: {
    title: 'Compétences et certifications',
    empty: 'Aucune compétence enregistrée',
    levels: { certified: 'Certifié', expert: 'Niveau expert', advanced: 'Avancé' },
    ruleTitle: 'Règle opérationnelle des baies',
    ruleText: (name: string, bay: string) =>
      `Les créneaux de service assignés à ${name} ne peuvent pas chevaucher la maintenance générale de ${bay}.`,
    ruleTextNoBay: (name: string) =>
      `Les créneaux de service assignés à ${name} ne peuvent pas chevaucher la maintenance générale.`,
    export: 'Exporter la fiche technique (PDF)',
  },
  form: {
    createTitle: 'Nouvel opérateur',
    editTitle: "Modifier l'opérateur",
    subtitle: "Enregistrez les données de l'opérateur et sa baie de travail.",
    name: 'Nom complet',
    accountHint: "Le compte avec lequel l'opérateur se connecte sera créé. Donnez-lui l'e-mail et le mot de passe temporaire.",
    firstName: 'Prénoms',
    lastName: 'Noms',
    document: 'Numéro de document',
    password: 'Mot de passe temporaire',
    showPassword: 'Afficher le mot de passe',
    creating: 'Création du compte...',
    namePlaceholder: 'Prénom et nom',
    specialty: 'Spécialité',
    specialtyPlaceholder: 'Ex. Détaillage céramique',
    phone: 'Téléphone',
    phonePlaceholder: '+57 300 000 0000',
    email: 'E-mail',
    emailPlaceholder: 'operateur@lavage.co',
    status: 'Statut',
    bay: 'Baie',
    noBay: 'Aucune baie assignée',
    bayNotApplicable: "Non applicable : l'opérateur est en arrêt maladie",
    tags: 'Étiquettes',
    addTag: 'Ajouter une étiquette',
    noTags: "Pas encore d'étiquettes.",
    tagPlaceholder: 'Ex. Polissage céramique',
    save: 'Enregistrer',
    errors: {
      name: 'Saisissez le nom complet',
      firstName: 'Saisissez les prénoms',
      lastName: 'Saisissez les noms',
      document: 'Doit contenir entre 5 et 20 chiffres',
      password: '8 caractères minimum, une majuscule, un chiffre et un caractère spécial',
      specialty: 'Saisissez la spécialité',
      phone: 'Saisissez un téléphone valide',
      email: "L'e-mail n'est pas valide",
    },
  },
  assign: {
    title: 'Assigner un horaire',
    subtitle: "Choisissez l'opérateur, son statut et la baie de l'horaire.",
    operator: 'Opérateur',
    status: 'Statut',
    bay: 'Baie',
    noBay: 'Aucune baie assignée',
    hint: "La baie ne peut pas être assignée quand l'opérateur est en arrêt.",
    submit: "Assigner l'horaire",
  },
  availability: {
    title: 'Disponibilité hebdomadaire',
    subtitle: "Définissez les horaires où l'opérateur assure des services.",
    hint: "Décochez le jour pour indiquer que l'opérateur ne travaille pas ce jour-là.",
    start: 'Début',
    end: 'Fin',
    error: 'Utilisez le format hh:mm et le début doit être avant la fin',
    save: 'Enregistrer',
  },
  absence: {
    title: 'Enregistrer un arrêt',
    subtitle: "Enregistrez la période où l'opérateur ne sera pas disponible.",
    start: 'Date de début',
    end: 'Date de fin',
    reason: 'Motif',
    reasonPlaceholder: 'Ex. Arrêt maladie',
    save: 'Enregistrer',
    errors: { date: 'Date invalide (jj/mm/aaaa)', range: 'La date de fin ne peut pas être avant le début' },
  },
  returnDialog: {
    title: 'Enregistrer le retour',
    message: (name: string) => `Confirmez-vous que ${name} reprend le travail ? Son statut passera à Disponible.`,
    confirm: 'Confirmer',
  },
  calendar: {
    open: 'Voir le calendrier des horaires',
    title: (name: string) => `Calendrier de ${name}`,
    subtitle: "Horaires, services et absences de l'opérateur",
    back: 'Retour à la fiche',
    weekLabel: (week: number, from: string, to: string) => `Semaine ${week} : ${from} – ${to}`,
    fullDay: (from: string, to: string) => `Journée complète : ${from} – ${to}`,
    views: { week: 'Semaine', day: 'Jour', month: 'Mois' },
    legend: { available: 'Disponible', service: 'Service assigné', leave: 'Absence approuvée', lunch: 'Déjeuner / pause' },
    today: "Aujourd'hui",
    free: 'Disponible',
    lunch: 'Déjeuner',
    dayOff: 'Ne travaille pas ce jour',
    blocks: (total: number) => (total === 1 ? '1 créneau' : `${total} créneaux`),
  },
};

const pt: typeof es = {
  title: 'Operadores',
  subtitle: 'Gerencie a equipe técnica, seus turnos e sua disponibilidade operacional em tempo real',
  assignShifts: 'Atribuir turnos',
  newOperator: 'Novo operador',
  inactiveTag: 'Inativo',
  manageInUsers: 'Os operadores são contas com a função Operador: crie e edite em Gestão → Usuários.',
  common: { cancel: 'Cancelar' },
  summary: {
    staff: 'Operadores no quadro',
    staffDetail: (hired: number, interns: number) => `${hired} contratados · ${interns} estagiários`,
    availableToday: 'Disponíveis hoje',
    availableDetail: (total: number) => `${total} no turno da tarde (14:00 - 22:00)`,
    weeklyServices: 'Serviços da semana',
    trend: (percent: number) => `${percent >= 0 ? '+' : ''}${percent}% vs semana anterior`,
    rating: 'Avaliação média',
    ratingBase: (total: number) => `Com base em ${total} avaliações de clientes`,
  },
  search: 'Buscar por nome ou especialidade...',
  filters: { all: 'Todos', available: 'Disponíveis', in_service: 'Em serviço', absent: 'Ausentes' },
  empty: 'Nenhum operador encontrado',
  emptyHint: 'Tente mudar a busca ou o filtro',
  status: { available: 'Disponível', in_service: 'Em serviço', absent: 'Licença médica' },
  card: {
    rating: 'Avaliação dos clientes',
    noRating: 'Sem avaliações',
    bay: 'Baia atribuída',
    noBay: 'Sem atribuição',
    services: (total: number) => `${total} ${total === 1 ? 'serviço' : 'serviços'}`,
    servicesAbsent: (total: number, reason: string) => `${total} ${total === 1 ? 'serviço' : 'serviços'} (${reason})`,
    viewAvailability: 'Ver disponibilidade',
    registerReturn: 'Registrar retorno',
  },
  detail: {
    back: 'Voltar para Operadores',
    title: (name: string) => `Disponibilidade de ${name}`,
    idLabel: (code: string) => `ID: ${code}`,
    ratingLine: (rating: string, reviews: number) => `${rating} (${reviews} avaliações)`,
    bayLine: (bay: string) => `Baia atribuída: ${bay}`,
    registerAbsence: 'Registrar ausência',
    registerReturn: 'Registrar retorno',
    editAvailability: 'Editar disponibilidade',
    assignBay: 'Atribuir baia / turno',
    absentUntil: (date: string) => `Ausente até ${date}`,
  },
  metrics: {
    services: 'Serviços da semana',
    servicesUnit: 'serviços',
    hours: 'Horas disponíveis',
    hoursOf: (capacity: number) => `/ ${capacity} h`,
    occupied: (percent: number) => `${percent}% da capacidade operacional ocupada`,
    punctuality: 'Pontualidade',
    punctualityNote: 'Excelente registro de turnos',
    revenue: 'Receita gerada na semana',
    goal: (percent: number) => `${percent}% da meta semanal cumprida`,
  },
  today: {
    title: 'Histórico de serviços de hoje',
    assigned: (total: number) => `${total} ${total === 1 ? 'serviço atribuído' : 'serviços atribuídos'}`,
    subtitle: (bay: string) => `Gestão do fluxo de trabalho em tempo real para ${bay}`,
    subtitleNoBay: 'Gestão do fluxo de trabalho em tempo real',
    empty: 'Sem serviços atribuídos hoje',
    bay: 'Baia',
    status: { completed: 'Concluído', in_progress: 'Em andamento', scheduled: 'Agendado' },
    action: { completed: 'Detalhes', in_progress: 'Registro', scheduled: 'Ver ordem' },
    close: 'Fechar',
  },
  skills: {
    title: 'Habilidades e certificações',
    empty: 'Sem habilidades cadastradas',
    levels: { certified: 'Certificado', expert: 'Nível especialista', advanced: 'Avançado' },
    ruleTitle: 'Regra operacional das baias',
    ruleText: (name: string, bay: string) =>
      `Os blocos de serviço atribuídos a ${name} não podem se sobrepor aos turnos de manutenção geral em ${bay}.`,
    ruleTextNoBay: (name: string) =>
      `Os blocos de serviço atribuídos a ${name} não podem se sobrepor aos turnos de manutenção geral.`,
    export: 'Exportar ficha técnica (PDF)',
  },
  form: {
    createTitle: 'Novo operador',
    editTitle: 'Editar operador',
    subtitle: 'Cadastre os dados do operador e sua baia de trabalho.',
    name: 'Nome completo',
    accountHint: 'Será criada a conta com a qual o operador entra. Entregue a ele o e-mail e a senha temporária.',
    firstName: 'Nomes',
    lastName: 'Sobrenomes',
    document: 'Número do documento',
    password: 'Senha temporária',
    showPassword: 'Mostrar senha',
    creating: 'Criando conta...',
    namePlaceholder: 'Nome e sobrenome',
    specialty: 'Especialidade',
    specialtyPlaceholder: 'Ex. Detalhamento cerâmico',
    phone: 'Telefone',
    phonePlaceholder: '+57 300 000 0000',
    email: 'E-mail',
    emailPlaceholder: 'operador@lavajato.co',
    status: 'Status',
    bay: 'Baia',
    noBay: 'Sem baia atribuída',
    bayNotApplicable: 'Não se aplica: o operador está de licença médica',
    tags: 'Etiquetas',
    addTag: 'Adicionar etiqueta',
    noTags: 'Ainda não há etiquetas.',
    tagPlaceholder: 'Ex. Polimento cerâmico',
    save: 'Salvar',
    errors: {
      name: 'Informe o nome completo',
      firstName: 'Informe os nomes',
      lastName: 'Informe os sobrenomes',
      document: 'Deve ter entre 5 e 20 dígitos',
      password: 'Mínimo 8 caracteres, uma maiúscula, um número e um caractere especial',
      specialty: 'Informe a especialidade',
      phone: 'Informe um telefone válido',
      email: 'O e-mail não é válido',
    },
  },
  assign: {
    title: 'Atribuir turno',
    subtitle: 'Escolha o operador, seu status e a baia do turno.',
    operator: 'Operador',
    status: 'Status',
    bay: 'Baia',
    noBay: 'Sem baia atribuída',
    hint: 'A baia não pode ser atribuída quando o operador está de licença.',
    submit: 'Atribuir turno',
  },
  availability: {
    title: 'Disponibilidade semanal',
    subtitle: 'Defina os horários em que o operador atende serviços.',
    hint: 'Desmarque o dia para indicar que o operador não trabalha nesse dia.',
    start: 'Início',
    end: 'Fim',
    error: 'Use o formato hh:mm e o início deve ser antes do fim',
    save: 'Salvar',
  },
  absence: {
    title: 'Registrar licença',
    subtitle: 'Registre o período em que o operador não estará disponível.',
    start: 'Data de início',
    end: 'Data de fim',
    reason: 'Motivo',
    reasonPlaceholder: 'Ex. Licença médica',
    save: 'Salvar',
    errors: { date: 'Data inválida (dd/mm/aaaa)', range: 'A data de fim não pode ser anterior ao início' },
  },
  returnDialog: {
    title: 'Registrar retorno',
    message: (name: string) => `Confirma que ${name} voltou a trabalhar? O status passará para Disponível.`,
    confirm: 'Confirmar',
  },
  calendar: {
    open: 'Ver calendário de turnos',
    title: (name: string) => `Calendário de ${name}`,
    subtitle: 'Turnos, serviços e ausências do operador',
    back: 'Voltar para a ficha',
    weekLabel: (week: number, from: string, to: string) => `Semana ${week}: ${from} – ${to}`,
    fullDay: (from: string, to: string) => `Jornada completa: ${from} – ${to}`,
    views: { week: 'Semana', day: 'Dia', month: 'Mês' },
    legend: { available: 'Disponível', service: 'Serviço atribuído', leave: 'Ausência aprovada', lunch: 'Almoço / pausa' },
    today: 'Hoje',
    free: 'Disponível',
    lunch: 'Almoço',
    dayOff: 'Não trabalha neste dia',
    blocks: (total: number) => (total === 1 ? '1 bloco' : `${total} blocos`),
  },
};

export const OPERATOR_TEXTS = localized({ es, en, fr, pt });
