import { localized } from '../../../shared/i18n/localized';
import { PaymentMethod, PaymentStatus } from '../models/payment';

// Textos de la pantalla de pagos en los 4 idiomas de la app
const es = {
  title: 'Gestión y Verificación de Pagos',
  subtitle: 'Audita comprobantes bancarios, valida transferencias y controla recaudos diarios',
  export: 'Exportar conciliación',
  // encabezados del archivo CSV exportado
  csvHeaders: ['Código', 'Cliente', 'Documento', 'Teléfono', 'Referencia', 'Método', 'Monto', 'Monto declarado', 'Fecha', 'Hora', 'Servicio', 'Estado'],
  newPayment: 'Registrar pago manual',

  stats: {
    pending: 'Pendientes de revisión',
    pendingBadge: 'Atención prioritaria',
    approved: 'Aprobados hoy',
    rejected: 'Rechazados / inconsistentes',
    rejectedBadge: 'Comprobante inválido',
    collected: 'Recaudo total (día)',
    transactions: (total: number) => (total === 1 ? '1 transacción' : `${total} transacciones`),
  },

  filters: {
    search: 'Buscar por cliente, documento o referencia...',
    allMethods: 'Método: Todos',
    method: (label: string) => `Método: ${label}`,
    allStatuses: 'Todos los estados',
    clear: 'Limpiar filtros',
  },

  list: {
    count: (total: number) => (total === 1 ? '1 pago' : `${total} pagos`),
    empty: 'No se encontraron pagos',
    emptyHint: 'Prueba cambiando los filtros de búsqueda',
    review: 'Revisar',
    receipt: 'Recibo',
    reason: 'Ver motivo',
  },

  status: {
    pending: 'Pendiente',
    approved: 'Aprobado',
    rejected: 'Rechazado',
  } as Record<PaymentStatus, string>,

  // Nombre corto (tarjetas y filtros)
  methods: {
    cash: 'Efectivo',
    nequi: 'Nequi',
    daviplata: 'Daviplata',
    bancolombia: 'Bancolombia',
  } as Record<PaymentMethod, string>,

  // Nombre largo (formulario de pago manual)
  methodsForm: {
    cash: 'Efectivo',
    nequi: 'Nequi',
    daviplata: 'Daviplata',
    bancolombia: 'Transferencia Bancolombia',
  } as Record<PaymentMethod, string>,

  form: {
    title: 'Registrar pago manual',
    subtitle: 'Úsalo cuando un cliente pagó en caja y no quedó registrado por la app',
    customer: 'Cliente',
    customerPlaceholder: 'Nombre del cliente',
    service: 'Servicio',
    servicePlaceholder: 'Ej. Lavado Básico',
    amount: 'Monto (COP)',
    amountPlaceholder: '45.000',
    method: 'Método de pago',
    cancel: 'Cancelar',
    submit: 'Registrar pago',
  },

  review: {
    reviewTitle: (code: string) => `Revisar pago ${code}`,
    detailTitle: (code: string) => `Detalle del pago ${code}`,
    subtitle: 'Coteja el comprobante digital remitido por el cliente contra los datos registrados en la reserva',
    attachment: 'Comprobante adjunto',
    cashTitle: 'Pago recibido en caja',
    to: 'Para',
    taxId: 'NIT / Celular',
    reference: 'Referencia',
    dateTime: 'Fecha y hora',
    linkedAppointment: (code: string) => `Cita vinculada: ${code}`,
    document: 'Documento',
    serviceVehicle: 'Servicio y vehículo',
    scheduleBay: 'Horario y bahía',
    operator: 'Operario',
    reconciliation: 'Datos de conciliación bancaria',
    verified: 'Verificado contra pasarela',
    cashVerified: 'Recibido en caja',
    method: 'Método de pago',
    transactionRef: 'Referencia de transacción',
    comparison: 'Comparativa de montos',
    amountDue: 'Monto a pagar (servicio)',
    amountDeclared: 'Monto declarado en comprobante',
    matchTitle: '¡Los montos coinciden exactamente!',
    matchText: 'El pago cubre el 100% de la tarifa oficial pactada en la reserva.',
    matchChip: 'Conforme (0% diferencia)',
    mismatchTitle: '¡Los montos no coinciden!',
    below: (amount: string) => `El comprobante está ${amount} por debajo de la tarifa pactada.`,
    above: (amount: string) => `El comprobante está ${amount} por encima de la tarifa pactada.`,
    mismatchChip: (percent: string) => `Inconsistente (${percent}% diferencia)`,
    rejectionSection: 'Motivo del rechazo',
    reasonLabel: 'Motivo del rechazo',
    reasonPlaceholder: 'Explica por qué se rechaza este pago',
    reasonError: 'Escribe un motivo de al menos 5 caracteres',
    auditedBy: (name: string) => `Operación auditada por: ${name}`,
    close: 'Cerrar',
    reject: 'Rechazar',
    approve: 'Aprobar pago',
    back: 'Volver',
    confirmReject: 'Confirmar rechazo',
    shareReceipt: 'Compartir recibo',
    receiptTitle: 'Recibo de pago',
    customer: 'Cliente',
    service: 'Servicio',
    amount: 'Monto',
  },
};

const en: typeof es = {
  title: 'Payment Management and Verification',
  subtitle: 'Audit bank receipts, validate transfers and control daily collections',
  export: 'Export reconciliation',
  // encabezados del archivo CSV exportado
  csvHeaders: ['Code', 'Customer', 'Document', 'Phone', 'Reference', 'Method', 'Amount', 'Declared amount', 'Date', 'Time', 'Service', 'Status'],
  newPayment: 'Register manual payment',
  stats: {
    pending: 'Pending review',
    pendingBadge: 'Priority attention',
    approved: 'Approved today',
    rejected: 'Rejected / inconsistent',
    rejectedBadge: 'Invalid receipt',
    collected: 'Total collected (day)',
    transactions: (total: number) => (total === 1 ? '1 transaction' : `${total} transactions`),
  },
  filters: {
    search: 'Search by customer, document or reference...',
    allMethods: 'Method: All',
    method: (label: string) => `Method: ${label}`,
    allStatuses: 'All statuses',
    clear: 'Clear filters',
  },
  list: {
    count: (total: number) => (total === 1 ? '1 payment' : `${total} payments`),
    empty: 'No payments found',
    emptyHint: 'Try changing the search filters',
    review: 'Review',
    receipt: 'Receipt',
    reason: 'See reason',
  },
  status: { pending: 'Pending', approved: 'Approved', rejected: 'Rejected' },
  methods: { cash: 'Cash', nequi: 'Nequi', daviplata: 'Daviplata', bancolombia: 'Bancolombia' },
  methodsForm: { cash: 'Cash', nequi: 'Nequi', daviplata: 'Daviplata', bancolombia: 'Bancolombia transfer' },
  form: {
    title: 'Register manual payment',
    subtitle: 'Use it when a customer paid at the counter and it was not recorded in the app',
    customer: 'Customer',
    customerPlaceholder: 'Customer name',
    service: 'Service',
    servicePlaceholder: 'E.g. Basic Wash',
    amount: 'Amount (COP)',
    amountPlaceholder: '45,000',
    method: 'Payment method',
    cancel: 'Cancel',
    submit: 'Register payment',
  },
  review: {
    reviewTitle: (code: string) => `Review payment ${code}`,
    detailTitle: (code: string) => `Payment detail ${code}`,
    subtitle: 'Compare the digital receipt sent by the customer against the booking data',
    attachment: 'Attached receipt',
    cashTitle: 'Payment received at the counter',
    to: 'To',
    taxId: 'Tax ID / Mobile',
    reference: 'Reference',
    dateTime: 'Date and time',
    linkedAppointment: (code: string) => `Linked appointment: ${code}`,
    document: 'Document',
    serviceVehicle: 'Service and vehicle',
    scheduleBay: 'Time and bay',
    operator: 'Operator',
    reconciliation: 'Bank reconciliation data',
    verified: 'Verified against gateway',
    cashVerified: 'Received at the counter',
    method: 'Payment method',
    transactionRef: 'Transaction reference',
    comparison: 'Amount comparison',
    amountDue: 'Amount due (service)',
    amountDeclared: 'Amount declared on receipt',
    matchTitle: 'The amounts match exactly!',
    matchText: 'The payment covers 100% of the official rate agreed in the booking.',
    matchChip: 'Compliant (0% difference)',
    mismatchTitle: 'The amounts do not match!',
    below: (amount: string) => `The receipt is ${amount} below the agreed rate.`,
    above: (amount: string) => `The receipt is ${amount} above the agreed rate.`,
    mismatchChip: (percent: string) => `Inconsistent (${percent}% difference)`,
    rejectionSection: 'Rejection reason',
    reasonLabel: 'Rejection reason',
    reasonPlaceholder: 'Explain why this payment is rejected',
    reasonError: 'Write a reason of at least 5 characters',
    auditedBy: (name: string) => `Operation audited by: ${name}`,
    close: 'Close',
    reject: 'Reject',
    approve: 'Approve payment',
    back: 'Back',
    confirmReject: 'Confirm rejection',
    shareReceipt: 'Share receipt',
    receiptTitle: 'Payment receipt',
    customer: 'Customer',
    service: 'Service',
    amount: 'Amount',
  },
};

const fr: typeof es = {
  title: 'Gestion et vérification des paiements',
  subtitle: 'Auditez les justificatifs bancaires, validez les virements et contrôlez les encaissements du jour',
  export: 'Exporter le rapprochement',
  // encabezados del archivo CSV exportado
  csvHeaders: ['Code', 'Client', 'Document', 'Téléphone', 'Référence', 'Méthode', 'Montant', 'Montant déclaré', 'Date', 'Heure', 'Service', 'Statut'],
  newPayment: 'Enregistrer un paiement manuel',
  stats: {
    pending: 'En attente de révision',
    pendingBadge: 'Attention prioritaire',
    approved: "Approuvés aujourd'hui",
    rejected: 'Refusés / incohérents',
    rejectedBadge: 'Justificatif invalide',
    collected: 'Total encaissé (jour)',
    transactions: (total: number) => (total === 1 ? '1 transaction' : `${total} transactions`),
  },
  filters: {
    search: 'Rechercher par client, document ou référence...',
    allMethods: 'Méthode : toutes',
    method: (label: string) => `Méthode : ${label}`,
    allStatuses: 'Tous les statuts',
    clear: 'Effacer les filtres',
  },
  list: {
    count: (total: number) => (total === 1 ? '1 paiement' : `${total} paiements`),
    empty: 'Aucun paiement trouvé',
    emptyHint: 'Essayez de modifier les filtres de recherche',
    review: 'Réviser',
    receipt: 'Reçu',
    reason: 'Voir le motif',
  },
  status: { pending: 'En attente', approved: 'Approuvé', rejected: 'Refusé' },
  methods: { cash: 'Espèces', nequi: 'Nequi', daviplata: 'Daviplata', bancolombia: 'Bancolombia' },
  methodsForm: { cash: 'Espèces', nequi: 'Nequi', daviplata: 'Daviplata', bancolombia: 'Virement Bancolombia' },
  form: {
    title: 'Enregistrer un paiement manuel',
    subtitle: "À utiliser quand un client a payé en caisse et que ce n'est pas enregistré dans l'application",
    customer: 'Client',
    customerPlaceholder: 'Nom du client',
    service: 'Service',
    servicePlaceholder: 'Ex. Lavage basique',
    amount: 'Montant (COP)',
    amountPlaceholder: '45 000',
    method: 'Moyen de paiement',
    cancel: 'Annuler',
    submit: 'Enregistrer le paiement',
  },
  review: {
    reviewTitle: (code: string) => `Réviser le paiement ${code}`,
    detailTitle: (code: string) => `Détail du paiement ${code}`,
    subtitle: 'Comparez le justificatif envoyé par le client avec les données de la réservation',
    attachment: 'Justificatif joint',
    cashTitle: 'Paiement reçu en caisse',
    to: 'À',
    taxId: 'NIT / Mobile',
    reference: 'Référence',
    dateTime: 'Date et heure',
    linkedAppointment: (code: string) => `Rendez-vous lié : ${code}`,
    document: 'Document',
    serviceVehicle: 'Service et véhicule',
    scheduleBay: 'Horaire et baie',
    operator: 'Opérateur',
    reconciliation: 'Données de rapprochement bancaire',
    verified: 'Vérifié auprès de la passerelle',
    cashVerified: 'Reçu en caisse',
    method: 'Moyen de paiement',
    transactionRef: 'Référence de transaction',
    comparison: 'Comparaison des montants',
    amountDue: 'Montant à payer (service)',
    amountDeclared: 'Montant déclaré sur le justificatif',
    matchTitle: 'Les montants correspondent exactement !',
    matchText: 'Le paiement couvre 100 % du tarif officiel convenu dans la réservation.',
    matchChip: "Conforme (0 % d'écart)",
    mismatchTitle: 'Les montants ne correspondent pas !',
    below: (amount: string) => `Le justificatif est inférieur de ${amount} au tarif convenu.`,
    above: (amount: string) => `Le justificatif est supérieur de ${amount} au tarif convenu.`,
    mismatchChip: (percent: string) => `Incohérent (${percent} % d'écart)`,
    rejectionSection: 'Motif du refus',
    reasonLabel: 'Motif du refus',
    reasonPlaceholder: 'Expliquez pourquoi ce paiement est refusé',
    reasonError: "Écrivez un motif d'au moins 5 caractères",
    auditedBy: (name: string) => `Opération auditée par : ${name}`,
    close: 'Fermer',
    reject: 'Refuser',
    approve: 'Approuver le paiement',
    back: 'Retour',
    confirmReject: 'Confirmer le refus',
    shareReceipt: 'Partager le reçu',
    receiptTitle: 'Reçu de paiement',
    customer: 'Client',
    service: 'Service',
    amount: 'Montant',
  },
};

const pt: typeof es = {
  title: 'Gestão e Verificação de Pagamentos',
  subtitle: 'Audite comprovantes bancários, valide transferências e controle a arrecadação diária',
  export: 'Exportar conciliação',
  // encabezados del archivo CSV exportado
  csvHeaders: ['Código', 'Cliente', 'Documento', 'Telefone', 'Referência', 'Método', 'Valor', 'Valor declarado', 'Data', 'Hora', 'Serviço', 'Status'],
  newPayment: 'Registrar pagamento manual',
  stats: {
    pending: 'Pendentes de revisão',
    pendingBadge: 'Atenção prioritária',
    approved: 'Aprovados hoje',
    rejected: 'Rejeitados / inconsistentes',
    rejectedBadge: 'Comprovante inválido',
    collected: 'Arrecadação total (dia)',
    transactions: (total: number) => (total === 1 ? '1 transação' : `${total} transações`),
  },
  filters: {
    search: 'Buscar por cliente, documento ou referência...',
    allMethods: 'Método: Todos',
    method: (label: string) => `Método: ${label}`,
    allStatuses: 'Todos os status',
    clear: 'Limpar filtros',
  },
  list: {
    count: (total: number) => (total === 1 ? '1 pagamento' : `${total} pagamentos`),
    empty: 'Nenhum pagamento encontrado',
    emptyHint: 'Tente mudar os filtros de busca',
    review: 'Revisar',
    receipt: 'Recibo',
    reason: 'Ver motivo',
  },
  status: { pending: 'Pendente', approved: 'Aprovado', rejected: 'Rejeitado' },
  methods: { cash: 'Dinheiro', nequi: 'Nequi', daviplata: 'Daviplata', bancolombia: 'Bancolombia' },
  methodsForm: { cash: 'Dinheiro', nequi: 'Nequi', daviplata: 'Daviplata', bancolombia: 'Transferência Bancolombia' },
  form: {
    title: 'Registrar pagamento manual',
    subtitle: 'Use quando um cliente pagou no caixa e não ficou registrado no app',
    customer: 'Cliente',
    customerPlaceholder: 'Nome do cliente',
    service: 'Serviço',
    servicePlaceholder: 'Ex. Lavagem Básica',
    amount: 'Valor (COP)',
    amountPlaceholder: '45.000',
    method: 'Forma de pagamento',
    cancel: 'Cancelar',
    submit: 'Registrar pagamento',
  },
  review: {
    reviewTitle: (code: string) => `Revisar pagamento ${code}`,
    detailTitle: (code: string) => `Detalhe do pagamento ${code}`,
    subtitle: 'Compare o comprovante enviado pelo cliente com os dados registrados na reserva',
    attachment: 'Comprovante anexado',
    cashTitle: 'Pagamento recebido no caixa',
    to: 'Para',
    taxId: 'CNPJ / Celular',
    reference: 'Referência',
    dateTime: 'Data e hora',
    linkedAppointment: (code: string) => `Agendamento vinculado: ${code}`,
    document: 'Documento',
    serviceVehicle: 'Serviço e veículo',
    scheduleBay: 'Horário e baia',
    operator: 'Operador',
    reconciliation: 'Dados de conciliação bancária',
    verified: 'Verificado no gateway',
    cashVerified: 'Recebido no caixa',
    method: 'Forma de pagamento',
    transactionRef: 'Referência da transação',
    comparison: 'Comparação de valores',
    amountDue: 'Valor a pagar (serviço)',
    amountDeclared: 'Valor declarado no comprovante',
    matchTitle: 'Os valores coincidem exatamente!',
    matchText: 'O pagamento cobre 100% da tarifa oficial acordada na reserva.',
    matchChip: 'Conforme (0% de diferença)',
    mismatchTitle: 'Os valores não coincidem!',
    below: (amount: string) => `O comprovante está ${amount} abaixo da tarifa acordada.`,
    above: (amount: string) => `O comprovante está ${amount} acima da tarifa acordada.`,
    mismatchChip: (percent: string) => `Inconsistente (${percent}% de diferença)`,
    rejectionSection: 'Motivo da rejeição',
    reasonLabel: 'Motivo da rejeição',
    reasonPlaceholder: 'Explique por que este pagamento é rejeitado',
    reasonError: 'Escreva um motivo de pelo menos 5 caracteres',
    auditedBy: (name: string) => `Operação auditada por: ${name}`,
    close: 'Fechar',
    reject: 'Rejeitar',
    approve: 'Aprovar pagamento',
    back: 'Voltar',
    confirmReject: 'Confirmar rejeição',
    shareReceipt: 'Compartilhar recibo',
    receiptTitle: 'Recibo de pagamento',
    customer: 'Cliente',
    service: 'Serviço',
    amount: 'Valor',
  },
};

export const PAYMENT_TEXTS = localized({ es, en, fr, pt });
