import { ReservationStatus } from '../models/reservation';

// Textos de la pantalla de reservas (centralizados para migrarlos fácil a i18n)
export const TEXTS = {
  title: 'Gestión de Reservas',
  subtitle: 'Monitorea, asigna operarios y gestiona el flujo de servicios en tiempo real',
  export: 'Exportar',
  newReservation: 'Nueva Reserva',

  stats: {
    total: 'Total reservas hoy',
    active: 'Confirmadas / en progreso',
    unassigned: 'Por asignar operario',
    cancelled: 'Canceladas / reprog.',
    attention: 'Atención requerida',
  },

  filters: {
    search: 'Buscar por cliente o placa...',
    datePlaceholder: 'dd/mm/aaaa',
    today: 'Hoy',
    allStatuses: 'Todos los estados',
    allOperators: 'Todos los operarios',
    unassigned: 'Sin asignar',
    clear: 'Limpiar',
  },

  list: {
    count: (total: number) => (total === 1 ? '1 reserva' : `${total} reservas`),
    empty: 'No se encontraron reservas',
    emptyHint: 'Prueba cambiando los filtros de búsqueda',
  },

  status: {
    confirmed: 'Confirmada',
    in_progress: 'En progreso',
    completed: 'Completada',
    cancelled: 'Cancelada',
    rescheduled: 'Reprogramada',
  } as Record<ReservationStatus, string>,

  form: {
    createTitle: 'Nueva reserva',
    editTitle: 'Editar reserva',
    subtitle: 'Registra un servicio en la agenda del lavadero.',
    customer: 'Cliente',
    phone: 'Teléfono',
    email: 'Correo electrónico',
    vehicle: 'Vehículo',
    plate: 'Placa',
    service: 'Servicio',
    date: 'Fecha',
    time: 'Hora',
    duration: 'Duración (min)',
    bay: 'Bahía',
    operator: 'Operario',
    status: 'Estado',
    notes: 'Notas',
    customerPlaceholder: 'Nombre completo del cliente',
    phonePlaceholder: '+57 300 000 0000',
    emailPlaceholder: 'cliente@correo.com',
    vehiclePlaceholder: 'Marca y modelo',
    platePlaceholder: 'ABC-123',
    notesPlaceholder: 'Indicaciones o preferencias del cliente',
    noBay: 'Sin bahía',
    noOperator: 'Sin operario',
    cancel: 'Cancelar',
    create: 'Crear reserva',
    save: 'Guardar',
    errors: {
      customer: 'Ingresa el nombre completo',
      phone: 'Ingresa un teléfono válido',
      email: 'El correo no es válido',
      vehicle: 'Ingresa el vehículo',
      plate: 'Ingresa la placa',
      service: 'Selecciona un servicio',
      date: 'Fecha inválida (dd/mm/aaaa)',
      time: 'Hora inválida (hh:mm)',
      duration: 'Duración inválida',
    },
  },

  detail: {
    customerSection: 'Cliente',
    vehicleSection: 'Vehículo y servicio',
    scheduleSection: 'Agenda',
    notesSection: 'Notas',
    name: 'Nombre',
    phone: 'Teléfono',
    email: 'Correo',
    vehicle: 'Vehículo',
    plate: 'Placa',
    service: 'Servicio',
    duration: 'Duración',
    date: 'Fecha',
    schedule: 'Horario',
    bay: 'Bahía',
    operator: 'Operario',
    noEmail: 'Sin correo',
    noBay: 'Sin bahía',
    unassigned: 'Sin asignar',
    noNotes: 'Sin notas',
    close: 'Cerrar',
    edit: 'Editar reserva',
  },
};
