import { localized } from '../../../shared/i18n/localized';
import { ReservationStatus } from '../models/reservation';

// Textos de la pantalla de reservas en los 4 idiomas de la app
const es = {
  title: 'Gestión de Reservas',
  subtitle: 'Monitorea, asigna operarios y gestiona el flujo de servicios en tiempo real',
  export: 'Exportar',
  // encabezados del archivo CSV exportado
  csvHeaders: ['Código', 'Cliente', 'Teléfono', 'Vehículo', 'Placa', 'Servicio', 'Fecha', 'Hora', 'Operario', 'Estado'],
  newReservation: 'Nueva Reserva',

  stats: {
    total: 'Total reservas hoy',
    active: 'Confirmadas / en progreso',
    unassigned: 'Por asignar operario',
    cancelled: 'Canceladas / reprog.',
    attention: 'Atención requerida',
  },

  filters: {
    search: 'Buscar por cliente o placa...',
    datePlaceholder: 'dd/mm/aaaa',
    today: 'Hoy',
    allStatuses: 'Todos los estados',
    allOperators: 'Todos los operarios',
    unassigned: 'Sin asignar',
    clear: 'Limpiar',
  },

  list: {
    count: (total: number) => (total === 1 ? '1 reserva' : `${total} reservas`),
    empty: 'No se encontraron reservas',
    emptyHint: 'Prueba cambiando los filtros de búsqueda',
    assign: 'Asignar',
  },

  status: {
    confirmed: 'Confirmada',
    in_progress: 'En progreso',
    completed: 'Completada',
    cancelled: 'Cancelada',
    rescheduled: 'Reprogramada',
  } as Record<ReservationStatus, string>,

  form: {
    createTitle: 'Nueva reserva',
    editTitle: 'Editar reserva',
    subtitle: 'Registra un servicio en la agenda del lavadero.',
    customer: 'Cliente',
    phone: 'Teléfono',
    email: 'Correo electrónico',
    vehicle: 'Vehículo',
    plate: 'Placa',
    service: 'Servicio',
    date: 'Fecha',
    time: 'Hora',
    duration: 'Duración (min)',
    bay: 'Bahía',
    operator: 'Operario',
    status: 'Estado',
    notes: 'Notas',
    customerPlaceholder: 'Nombre completo del cliente',
    phonePlaceholder: '+57 300 000 0000',
    emailPlaceholder: 'cliente@correo.com',
    vehiclePlaceholder: 'Marca y modelo',
    platePlaceholder: 'ABC-123',
    notesPlaceholder: 'Indicaciones o preferencias del cliente',
    noBay: 'Sin bahía',
    noOperator: 'Sin operario',
    cancel: 'Cancelar',
    create: 'Crear reserva',
    save: 'Guardar',
    errors: {
      customer: 'Ingresa el nombre completo',
      phone: 'Ingresa un teléfono válido',
      email: 'El correo no es válido',
      vehicle: 'Ingresa el vehículo',
      plate: 'Ingresa la placa',
      service: 'Selecciona un servicio',
      date: 'Fecha inválida (dd/mm/aaaa)',
      time: 'Hora inválida (hh:mm)',
      duration: 'Duración inválida',
    },
  },

  detail: {
    customerSection: 'Cliente',
    vehicleSection: 'Vehículo y servicio',
    scheduleSection: 'Agenda',
    notesSection: 'Notas',
    name: 'Nombre',
    phone: 'Teléfono',
    email: 'Correo',
    vehicle: 'Vehículo',
    plate: 'Placa',
    service: 'Servicio',
    duration: 'Duración',
    date: 'Fecha',
    schedule: 'Horario',
    bay: 'Bahía',
    operator: 'Operario',
    noEmail: 'Sin correo',
    noBay: 'Sin bahía',
    unassigned: 'Sin asignar',
    noNotes: 'Sin notas',
    close: 'Cerrar',
    edit: 'Editar reserva',
    assign: 'Asignar operario',
  },

  // ---------------- Modal "Asignar operario" (assign-operator-modal de la web) ----------------
  assign: {
    title: 'Asignar operario',
    subtitle: (code: string) => `Elige quién atenderá la reserva ${code}.`,
    available: 'Disponible',
    busy: 'Ocupado',
    off: 'No disponible',
    servicesToday: (total: number) => (total === 1 ? '1 servicio hoy' : `${total} servicios hoy`),
    empty: 'No hay operarios registrados',
    cancel: 'Cancelar',
    confirm: 'Asignar',
    successTitle: '¡Operario asignado!',
    successMessage: (operator: string, code: string) => `${operator} atenderá la reserva ${code}.`,
  },
};

const en: typeof es = {
  title: 'Booking Management',
  subtitle: 'Monitor, assign operators and manage the service flow in real time',
  export: 'Export',
  // encabezados del archivo CSV exportado
  csvHeaders: ['Code', 'Customer', 'Phone', 'Vehicle', 'Plate', 'Service', 'Date', 'Time', 'Operator', 'Status'],
  newReservation: 'New Booking',
  stats: {
    total: 'Total bookings today',
    active: 'Confirmed / in progress',
    unassigned: 'Awaiting operator',
    cancelled: 'Cancelled / resched.',
    attention: 'Needs attention',
  },
  filters: {
    search: 'Search by customer or plate...',
    datePlaceholder: 'dd/mm/yyyy',
    today: 'Today',
    allStatuses: 'All statuses',
    allOperators: 'All operators',
    unassigned: 'Unassigned',
    clear: 'Clear',
  },
  list: {
    count: (total: number) => (total === 1 ? '1 booking' : `${total} bookings`),
    empty: 'No bookings found',
    emptyHint: 'Try changing the search filters',
    assign: 'Assign',
  },
  status: {
    confirmed: 'Confirmed',
    in_progress: 'In progress',
    completed: 'Completed',
    cancelled: 'Cancelled',
    rescheduled: 'Rescheduled',
  },
  form: {
    createTitle: 'New booking',
    editTitle: 'Edit booking',
    subtitle: 'Register a service in the car wash schedule.',
    customer: 'Customer',
    phone: 'Phone',
    email: 'Email',
    vehicle: 'Vehicle',
    plate: 'Plate',
    service: 'Service',
    date: 'Date',
    time: 'Time',
    duration: 'Duration (min)',
    bay: 'Bay',
    operator: 'Operator',
    status: 'Status',
    notes: 'Notes',
    customerPlaceholder: 'Customer full name',
    phonePlaceholder: '+57 300 000 0000',
    emailPlaceholder: 'customer@email.com',
    vehiclePlaceholder: 'Make and model',
    platePlaceholder: 'ABC-123',
    notesPlaceholder: 'Customer instructions or preferences',
    noBay: 'No bay',
    noOperator: 'No operator',
    cancel: 'Cancel',
    create: 'Create booking',
    save: 'Save',
    errors: {
      customer: 'Enter the full name',
      phone: 'Enter a valid phone number',
      email: 'The email is not valid',
      vehicle: 'Enter the vehicle',
      plate: 'Enter the plate',
      service: 'Select a service',
      date: 'Invalid date (dd/mm/yyyy)',
      time: 'Invalid time (hh:mm)',
      duration: 'Invalid duration',
    },
  },
  detail: {
    customerSection: 'Customer',
    vehicleSection: 'Vehicle and service',
    scheduleSection: 'Schedule',
    notesSection: 'Notes',
    name: 'Name',
    phone: 'Phone',
    email: 'Email',
    vehicle: 'Vehicle',
    plate: 'Plate',
    service: 'Service',
    duration: 'Duration',
    date: 'Date',
    schedule: 'Time slot',
    bay: 'Bay',
    operator: 'Operator',
    noEmail: 'No email',
    noBay: 'No bay',
    unassigned: 'Unassigned',
    noNotes: 'No notes',
    close: 'Close',
    edit: 'Edit booking',
    assign: 'Assign operator',
  },
  assign: {
    title: 'Assign operator',
    subtitle: (code: string) => `Choose who will handle booking ${code}.`,
    available: 'Available',
    busy: 'Busy',
    off: 'Unavailable',
    servicesToday: (total: number) => (total === 1 ? '1 service today' : `${total} services today`),
    empty: 'There are no registered operators',
    cancel: 'Cancel',
    confirm: 'Assign',
    successTitle: 'Operator assigned!',
    successMessage: (operator: string, code: string) => `${operator} will handle booking ${code}.`,
  },
};

const fr: typeof es = {
  title: 'Gestion des réservations',
  subtitle: 'Suivez, assignez des opérateurs et gérez le flux des services en temps réel',
  export: 'Exporter',
  // encabezados del archivo CSV exportado
  csvHeaders: ['Code', 'Client', 'Téléphone', 'Véhicule', 'Plaque', 'Service', 'Date', 'Heure', 'Opérateur', 'Statut'],
  newReservation: 'Nouvelle réservation',
  stats: {
    total: 'Réservations du jour',
    active: 'Confirmées / en cours',
    unassigned: 'Sans opérateur',
    cancelled: 'Annulées / reprog.',
    attention: 'Attention requise',
  },
  filters: {
    search: 'Rechercher par client ou plaque...',
    datePlaceholder: 'jj/mm/aaaa',
    today: 'Aujourd’hui',
    allStatuses: 'Tous les statuts',
    allOperators: 'Tous les opérateurs',
    unassigned: 'Non assignée',
    clear: 'Effacer',
  },
  list: {
    count: (total: number) => (total === 1 ? '1 réservation' : `${total} réservations`),
    empty: 'Aucune réservation trouvée',
    emptyHint: 'Essayez de modifier les filtres de recherche',
    assign: 'Assigner',
  },
  status: {
    confirmed: 'Confirmée',
    in_progress: 'En cours',
    completed: 'Terminée',
    cancelled: 'Annulée',
    rescheduled: 'Reprogrammée',
  },
  form: {
    createTitle: 'Nouvelle réservation',
    editTitle: 'Modifier la réservation',
    subtitle: 'Enregistrez un service dans l’agenda du lavage.',
    customer: 'Client',
    phone: 'Téléphone',
    email: 'E-mail',
    vehicle: 'Véhicule',
    plate: 'Plaque',
    service: 'Service',
    date: 'Date',
    time: 'Heure',
    duration: 'Durée (min)',
    bay: 'Baie',
    operator: 'Opérateur',
    status: 'Statut',
    notes: 'Notes',
    customerPlaceholder: 'Nom complet du client',
    phonePlaceholder: '+57 300 000 0000',
    emailPlaceholder: 'client@email.com',
    vehiclePlaceholder: 'Marque et modèle',
    platePlaceholder: 'ABC-123',
    notesPlaceholder: 'Indications ou préférences du client',
    noBay: 'Sans baie',
    noOperator: 'Sans opérateur',
    cancel: 'Annuler',
    create: 'Créer la réservation',
    save: 'Enregistrer',
    errors: {
      customer: 'Saisissez le nom complet',
      phone: 'Saisissez un téléphone valide',
      email: 'L’e-mail n’est pas valide',
      vehicle: 'Saisissez le véhicule',
      plate: 'Saisissez la plaque',
      service: 'Sélectionnez un service',
      date: 'Date invalide (jj/mm/aaaa)',
      time: 'Heure invalide (hh:mm)',
      duration: 'Durée invalide',
    },
  },
  detail: {
    customerSection: 'Client',
    vehicleSection: 'Véhicule et service',
    scheduleSection: 'Agenda',
    notesSection: 'Notes',
    name: 'Nom',
    phone: 'Téléphone',
    email: 'E-mail',
    vehicle: 'Véhicule',
    plate: 'Plaque',
    service: 'Service',
    duration: 'Durée',
    date: 'Date',
    schedule: 'Horaire',
    bay: 'Baie',
    operator: 'Opérateur',
    noEmail: 'Sans e-mail',
    noBay: 'Sans baie',
    unassigned: 'Non assignée',
    noNotes: 'Sans notes',
    close: 'Fermer',
    edit: 'Modifier la réservation',
    assign: 'Assigner un opérateur',
  },
  assign: {
    title: 'Assigner un opérateur',
    subtitle: (code: string) => `Choisissez qui s’occupera de la réservation ${code}.`,
    available: 'Disponible',
    busy: 'Occupé',
    off: 'Indisponible',
    servicesToday: (total: number) => (total === 1 ? '1 service aujourd’hui' : `${total} services aujourd’hui`),
    empty: 'Aucun opérateur enregistré',
    cancel: 'Annuler',
    confirm: 'Assigner',
    successTitle: 'Opérateur assigné !',
    successMessage: (operator: string, code: string) => `${operator} s’occupera de la réservation ${code}.`,
  },
};

const pt: typeof es = {
  title: 'Gestão de Reservas',
  subtitle: 'Monitore, atribua operadores e gerencie o fluxo de serviços em tempo real',
  export: 'Exportar',
  // encabezados del archivo CSV exportado
  csvHeaders: ['Código', 'Cliente', 'Telefone', 'Veículo', 'Placa', 'Serviço', 'Data', 'Hora', 'Operador', 'Status'],
  newReservation: 'Nova Reserva',
  stats: {
    total: 'Total de reservas hoje',
    active: 'Confirmadas / em andamento',
    unassigned: 'Sem operador',
    cancelled: 'Canceladas / reag.',
    attention: 'Atenção necessária',
  },
  filters: {
    search: 'Buscar por cliente ou placa...',
    datePlaceholder: 'dd/mm/aaaa',
    today: 'Hoje',
    allStatuses: 'Todos os status',
    allOperators: 'Todos os operadores',
    unassigned: 'Sem atribuição',
    clear: 'Limpar',
  },
  list: {
    count: (total: number) => (total === 1 ? '1 reserva' : `${total} reservas`),
    empty: 'Nenhuma reserva encontrada',
    emptyHint: 'Tente mudar os filtros de busca',
    assign: 'Atribuir',
  },
  status: {
    confirmed: 'Confirmada',
    in_progress: 'Em andamento',
    completed: 'Concluída',
    cancelled: 'Cancelada',
    rescheduled: 'Reagendada',
  },
  form: {
    createTitle: 'Nova reserva',
    editTitle: 'Editar reserva',
    subtitle: 'Registre um serviço na agenda do lava-rápido.',
    customer: 'Cliente',
    phone: 'Telefone',
    email: 'E-mail',
    vehicle: 'Veículo',
    plate: 'Placa',
    service: 'Serviço',
    date: 'Data',
    time: 'Hora',
    duration: 'Duração (min)',
    bay: 'Baia',
    operator: 'Operador',
    status: 'Status',
    notes: 'Observações',
    customerPlaceholder: 'Nome completo do cliente',
    phonePlaceholder: '+57 300 000 0000',
    emailPlaceholder: 'cliente@email.com',
    vehiclePlaceholder: 'Marca e modelo',
    platePlaceholder: 'ABC-123',
    notesPlaceholder: 'Indicações ou preferências do cliente',
    noBay: 'Sem baia',
    noOperator: 'Sem operador',
    cancel: 'Cancelar',
    create: 'Criar reserva',
    save: 'Salvar',
    errors: {
      customer: 'Informe o nome completo',
      phone: 'Informe um telefone válido',
      email: 'O e-mail não é válido',
      vehicle: 'Informe o veículo',
      plate: 'Informe a placa',
      service: 'Selecione um serviço',
      date: 'Data inválida (dd/mm/aaaa)',
      time: 'Hora inválida (hh:mm)',
      duration: 'Duração inválida',
    },
  },
  detail: {
    customerSection: 'Cliente',
    vehicleSection: 'Veículo e serviço',
    scheduleSection: 'Agenda',
    notesSection: 'Observações',
    name: 'Nome',
    phone: 'Telefone',
    email: 'E-mail',
    vehicle: 'Veículo',
    plate: 'Placa',
    service: 'Serviço',
    duration: 'Duração',
    date: 'Data',
    schedule: 'Horário',
    bay: 'Baia',
    operator: 'Operador',
    noEmail: 'Sem e-mail',
    noBay: 'Sem baia',
    unassigned: 'Sem atribuição',
    noNotes: 'Sem observações',
    close: 'Fechar',
    edit: 'Editar reserva',
    assign: 'Atribuir operador',
  },
  assign: {
    title: 'Atribuir operador',
    subtitle: (code: string) => `Escolha quem atenderá a reserva ${code}.`,
    available: 'Disponível',
    busy: 'Ocupado',
    off: 'Indisponível',
    servicesToday: (total: number) => (total === 1 ? '1 serviço hoje' : `${total} serviços hoje`),
    empty: 'Não há operadores cadastrados',
    cancel: 'Cancelar',
    confirm: 'Atribuir',
    successTitle: 'Operador atribuído!',
    successMessage: (operator: string, code: string) => `${operator} atenderá a reserva ${code}.`,
  },
};

export const TEXTS = localized({ es, en, fr, pt });
