import { localized } from '../../../shared/i18n/localized';
import { BayStatus, ExceptionType, ScheduleTab, WeekDay } from '../models/schedule';

// Textos de la pantalla de horarios y bahías en los 4 idiomas de la app
const es = {
  title: 'Horarios y bahías',
  subtitle:
    'Configura los turnos de atención comercial, días no laborables y la disponibilidad de las bahías de servicio',
  history: 'Historial',
  openToday: (range: string) => `Abierto hoy · ${range}`,
  closedToday: 'Cerrado hoy',

  common: {
    cancel: 'Cancelar',
    delete: 'Eliminar',
    close: 'Cerrar',
  },

  tabs: {
    hours: 'Horario del negocio',
    bays: 'Bahías de lavado',
  } as Record<ScheduleTab, string>,
  weeklyBadge: 'Semanal',
  activeBays: (total: number) => (total === 1 ? '1 activa' : `${total} activas`),

  days: {
    monday: 'Lunes',
    tuesday: 'Martes',
    wednesday: 'Miércoles',
    thursday: 'Jueves',
    friday: 'Viernes',
    saturday: 'Sábado',
    sunday: 'Domingo',
  } as Record<WeekDay, string>,

  // ---------------- Horario semanal ----------------
  week: {
    title: 'Horario semanal regular',
    description:
      'Define las horas de apertura y cierre para cada día de la semana. Los turnos de reserva se generarán dentro de este rango.',
    timezone: 'Zona horaria: America/Bogota (COT)',
    working: 'Laboral',
    rest: 'Descanso',
    opening: 'Apertura',
    closing: 'Cierre',
    pause: 'Pausa',
    noPause: 'Continuo (sin pausa)',
    notApplicable: 'No aplica',
    open: 'Abierto',
    closed: 'Cerrado',
    info: 'Los cambios impactan el motor de reservas en tiempo real.',
    reset: 'Restablecer valores',
    save: 'Guardar cambios',
    savedTitle: 'Horario guardado',
    savedMessage: 'Los cambios ya se aplican al motor de reservas.',
    invalidTitle: 'Revisa los horarios',
    invalidMessage: 'Corrige los días marcados en rojo antes de guardar.',
    errors: {
      time: 'Usa el formato hh:mm en 24 horas (ej. 18:30)',
      range: 'La apertura debe ser antes del cierre',
      pause: 'La pausa debe estar dentro del horario de atención',
    },
  },

  // ---------------- Excepciones ----------------
  exceptions: {
    title: 'Excepciones y días especiales',
    count: (total: number) => (total === 1 ? '1 programado' : `${total} programados`),
    subtitle:
      'Sobrescribe el horario habitual en feriados nacionales, mantenimientos programados o jornadas reducidas.',
    add: 'Agregar excepción',
    empty: 'No hay excepciones programadas',
    emptyHint: 'Agrega la primera con el botón de arriba',
    closedAllDay: 'Cerrado todo el día',
    types: {
      holiday: 'Festivo nacional',
      special: 'Horario especial',
      maintenance: 'Mantenimiento',
    } as Record<ExceptionType, string>,
    deleteTitle: 'Eliminar excepción',
    deleteMessage: (date: string) =>
      `¿Seguro que quieres eliminar la excepción del ${date}? Esta acción no se puede deshacer.`,
    form: {
      createTitle: 'Agregar excepción',
      editTitle: 'Editar excepción',
      date: 'Fecha',
      datePlaceholder: 'dd/mm/aaaa',
      type: 'Tipo',
      closedAllDay: 'Cerrado todo el día',
      opening: 'Apertura',
      closing: 'Cierre',
      description: 'Motivo / descripción',
      descriptionPlaceholder: 'Ej. Día de la Independencia de Cartagena',
      save: 'Guardar excepción',
      errors: {
        date: 'Fecha inválida (dd/mm/aaaa)',
        duplicate: 'Ya existe una excepción en esa fecha',
        time: 'Hora inválida (hh:mm)',
        range: 'La apertura debe ser antes del cierre',
      },
    },
    history: {
      added: 'Excepción agregada',
      updated: 'Excepción actualizada',
      deleted: 'Excepción eliminada',
    },
  },

  // ---------------- Bahías ----------------
  bays: {
    title: 'Bahías de lavado',
    subtitle: 'Activa, desactiva o pon en mantenimiento cada bahía física del local.',
    add: 'Agregar bahía',
    currentOperator: (name: string) => `Operario actual: ${name}`,
    unassigned: 'Sin asignar',
    state: 'Estado',
    empty: 'No hay bahías registradas',
    emptyHint: 'Agrega la primera con el botón de arriba',
    status: {
      active: 'Activa',
      maintenance: 'En mantenimiento',
      inactive: 'Inactiva',
    } as Record<BayStatus, string>,
    deleteTitle: 'Eliminar bahía',
    deleteMessage: (name: string) =>
      `¿Seguro que quieres eliminar ${name}? Esta acción no se puede deshacer.`,
    form: {
      createTitle: 'Agregar bahía',
      editTitle: 'Editar bahía',
      subtitle: 'Registra una nueva bahía o actualiza su estado y operario.',
      name: 'Nombre de la bahía',
      namePlaceholder: 'Ej. Bahía 5',
      status: 'Estado',
      operator: 'Operario asignado',
      create: 'Crear',
      save: 'Guardar cambios',
      errors: {
        name: 'Ingresa el nombre (mínimo 2 caracteres)',
        duplicate: 'Ya existe una bahía con ese nombre',
      },
    },
    history: {
      added: 'Bahía agregada',
      updated: 'Bahía actualizada',
      statusChanged: 'Estado de bahía actualizado',
      deleted: 'Bahía eliminada',
    },
  },

  // ---------------- Historial ----------------
  historyModal: {
    title: 'Historial de cambios',
    subtitle: 'Últimas modificaciones al horario del negocio',
    empty: 'Aún no hay cambios registrados',
    weekUpdated: 'Horario semanal actualizado',
  },
};

const en: typeof es = {
  title: 'Hours and bays',
  subtitle: 'Set business hours, non-working days and the availability of the service bays',
  history: 'History',
  openToday: (range: string) => `Open today · ${range}`,
  closedToday: 'Closed today',
  common: { cancel: 'Cancel', delete: 'Delete', close: 'Close' },
  tabs: { hours: 'Business hours', bays: 'Wash bays' },
  weeklyBadge: 'Weekly',
  activeBays: (total: number) => (total === 1 ? '1 active' : `${total} active`),
  days: {
    monday: 'Monday',
    tuesday: 'Tuesday',
    wednesday: 'Wednesday',
    thursday: 'Thursday',
    friday: 'Friday',
    saturday: 'Saturday',
    sunday: 'Sunday',
  },
  week: {
    title: 'Regular weekly schedule',
    description: 'Set the opening and closing time for each day of the week. Booking slots are generated within this range.',
    timezone: 'Time zone: America/Bogota (COT)',
    working: 'Working',
    rest: 'Day off',
    opening: 'Opening',
    closing: 'Closing',
    pause: 'Break',
    noPause: 'Continuous (no break)',
    notApplicable: 'Not applicable',
    open: 'Open',
    closed: 'Closed',
    info: 'Changes affect the booking engine in real time.',
    reset: 'Reset values',
    save: 'Save changes',
    savedTitle: 'Schedule saved',
    savedMessage: 'The changes now apply to the booking engine.',
    invalidTitle: 'Check the schedule',
    invalidMessage: 'Fix the days marked in red before saving.',
    errors: {
      time: 'Use the 24-hour hh:mm format (e.g. 18:30)',
      range: 'Opening must be before closing',
      pause: 'The break must be within business hours',
    },
  },
  exceptions: {
    title: 'Exceptions and special days',
    count: (total: number) => (total === 1 ? '1 scheduled' : `${total} scheduled`),
    subtitle: 'Override the usual schedule on national holidays, scheduled maintenance or reduced hours.',
    add: 'Add exception',
    empty: 'No exceptions scheduled',
    emptyHint: 'Add the first one with the button above',
    closedAllDay: 'Closed all day',
    types: { holiday: 'National holiday', special: 'Special hours', maintenance: 'Maintenance' },
    deleteTitle: 'Delete exception',
    deleteMessage: (date: string) => `Are you sure you want to delete the exception on ${date}? This action cannot be undone.`,
    form: {
      createTitle: 'Add exception',
      editTitle: 'Edit exception',
      date: 'Date',
      datePlaceholder: 'dd/mm/yyyy',
      type: 'Type',
      closedAllDay: 'Closed all day',
      opening: 'Opening',
      closing: 'Closing',
      description: 'Reason / description',
      descriptionPlaceholder: 'E.g. Cartagena Independence Day',
      save: 'Save exception',
      errors: {
        date: 'Invalid date (dd/mm/yyyy)',
        duplicate: 'An exception already exists on that date',
        time: 'Invalid time (hh:mm)',
        range: 'Opening must be before closing',
      },
    },
    history: { added: 'Exception added', updated: 'Exception updated', deleted: 'Exception deleted' },
  },
  bays: {
    title: 'Wash bays',
    subtitle: 'Enable, disable or put each physical bay of the shop under maintenance.',
    add: 'Add bay',
    currentOperator: (name: string) => `Current operator: ${name}`,
    unassigned: 'Unassigned',
    state: 'Status',
    empty: 'No bays registered',
    emptyHint: 'Add the first one with the button above',
    status: { active: 'Active', maintenance: 'Under maintenance', inactive: 'Inactive' },
    deleteTitle: 'Delete bay',
    deleteMessage: (name: string) => `Are you sure you want to delete ${name}? This action cannot be undone.`,
    form: {
      createTitle: 'Add bay',
      editTitle: 'Edit bay',
      subtitle: 'Register a new bay or update its status and operator.',
      name: 'Bay name',
      namePlaceholder: 'E.g. Bay 5',
      status: 'Status',
      operator: 'Assigned operator',
      create: 'Create',
      save: 'Save changes',
      errors: { name: 'Enter the name (at least 2 characters)', duplicate: 'A bay with that name already exists' },
    },
    history: { added: 'Bay added', updated: 'Bay updated', statusChanged: 'Bay status updated', deleted: 'Bay deleted' },
  },
  historyModal: {
    title: 'Change history',
    subtitle: 'Latest changes to the business hours',
    empty: 'No changes recorded yet',
    weekUpdated: 'Weekly schedule updated',
  },
};

const fr: typeof es = {
  title: 'Horaires et baies',
  subtitle: "Configurez les horaires d'ouverture, les jours non ouvrés et la disponibilité des baies de service",
  history: 'Historique',
  openToday: (range: string) => `Ouvert aujourd'hui · ${range}`,
  closedToday: "Fermé aujourd'hui",
  common: { cancel: 'Annuler', delete: 'Supprimer', close: 'Fermer' },
  tabs: { hours: "Horaires de l'entreprise", bays: 'Baies de lavage' },
  weeklyBadge: 'Hebdomadaire',
  activeBays: (total: number) => (total === 1 ? '1 active' : `${total} actives`),
  days: {
    monday: 'Lundi',
    tuesday: 'Mardi',
    wednesday: 'Mercredi',
    thursday: 'Jeudi',
    friday: 'Vendredi',
    saturday: 'Samedi',
    sunday: 'Dimanche',
  },
  week: {
    title: 'Horaire hebdomadaire habituel',
    description: "Définissez l'heure d'ouverture et de fermeture de chaque jour. Les créneaux de réservation sont générés dans cette plage.",
    timezone: 'Fuseau horaire : America/Bogota (COT)',
    working: 'Ouvré',
    rest: 'Repos',
    opening: 'Ouverture',
    closing: 'Fermeture',
    pause: 'Pause',
    noPause: 'Continu (sans pause)',
    notApplicable: 'Non applicable',
    open: 'Ouvert',
    closed: 'Fermé',
    info: 'Les changements affectent le moteur de réservations en temps réel.',
    reset: 'Réinitialiser',
    save: 'Enregistrer',
    savedTitle: 'Horaire enregistré',
    savedMessage: "Les changements s'appliquent déjà au moteur de réservations.",
    invalidTitle: 'Vérifiez les horaires',
    invalidMessage: 'Corrigez les jours marqués en rouge avant d’enregistrer.',
    errors: {
      time: 'Utilisez le format hh:mm sur 24 h (ex. 18:30)',
      range: "L'ouverture doit être avant la fermeture",
      pause: "La pause doit être dans les horaires d'ouverture",
    },
  },
  exceptions: {
    title: 'Exceptions et jours spéciaux',
    count: (total: number) => (total === 1 ? '1 programmée' : `${total} programmées`),
    subtitle: "Remplacez l'horaire habituel les jours fériés, lors de maintenances ou de journées réduites.",
    add: 'Ajouter une exception',
    empty: 'Aucune exception programmée',
    emptyHint: 'Ajoutez la première avec le bouton ci-dessus',
    closedAllDay: 'Fermé toute la journée',
    types: { holiday: 'Jour férié national', special: 'Horaire spécial', maintenance: 'Maintenance' },
    deleteTitle: "Supprimer l'exception",
    deleteMessage: (date: string) => `Voulez-vous vraiment supprimer l'exception du ${date} ? Cette action est irréversible.`,
    form: {
      createTitle: 'Ajouter une exception',
      editTitle: "Modifier l'exception",
      date: 'Date',
      datePlaceholder: 'jj/mm/aaaa',
      type: 'Type',
      closedAllDay: 'Fermé toute la journée',
      opening: 'Ouverture',
      closing: 'Fermeture',
      description: 'Motif / description',
      descriptionPlaceholder: "Ex. Fête de l'indépendance de Carthagène",
      save: "Enregistrer l'exception",
      errors: {
        date: 'Date invalide (jj/mm/aaaa)',
        duplicate: 'Une exception existe déjà à cette date',
        time: 'Heure invalide (hh:mm)',
        range: "L'ouverture doit être avant la fermeture",
      },
    },
    history: { added: 'Exception ajoutée', updated: 'Exception modifiée', deleted: 'Exception supprimée' },
  },
  bays: {
    title: 'Baies de lavage',
    subtitle: 'Activez, désactivez ou mettez en maintenance chaque baie physique du local.',
    add: 'Ajouter une baie',
    currentOperator: (name: string) => `Opérateur actuel : ${name}`,
    unassigned: 'Non assignée',
    state: 'Statut',
    empty: 'Aucune baie enregistrée',
    emptyHint: 'Ajoutez la première avec le bouton ci-dessus',
    status: { active: 'Active', maintenance: 'En maintenance', inactive: 'Inactive' },
    deleteTitle: 'Supprimer la baie',
    deleteMessage: (name: string) => `Voulez-vous vraiment supprimer ${name} ? Cette action est irréversible.`,
    form: {
      createTitle: 'Ajouter une baie',
      editTitle: 'Modifier la baie',
      subtitle: 'Enregistrez une nouvelle baie ou modifiez son statut et son opérateur.',
      name: 'Nom de la baie',
      namePlaceholder: 'Ex. Baie 5',
      status: 'Statut',
      operator: 'Opérateur assigné',
      create: 'Créer',
      save: 'Enregistrer',
      errors: { name: 'Saisissez le nom (2 caractères minimum)', duplicate: 'Une baie porte déjà ce nom' },
    },
    history: { added: 'Baie ajoutée', updated: 'Baie modifiée', statusChanged: 'Statut de la baie modifié', deleted: 'Baie supprimée' },
  },
  historyModal: {
    title: 'Historique des modifications',
    subtitle: "Dernières modifications des horaires de l'entreprise",
    empty: 'Aucune modification enregistrée',
    weekUpdated: 'Horaire hebdomadaire modifié',
  },
};

const pt: typeof es = {
  title: 'Horários e baias',
  subtitle: 'Configure o horário de atendimento, os dias sem expediente e a disponibilidade das baias de serviço',
  history: 'Histórico',
  openToday: (range: string) => `Aberto hoje · ${range}`,
  closedToday: 'Fechado hoje',
  common: { cancel: 'Cancelar', delete: 'Excluir', close: 'Fechar' },
  tabs: { hours: 'Horário do negócio', bays: 'Baias de lavagem' },
  weeklyBadge: 'Semanal',
  activeBays: (total: number) => (total === 1 ? '1 ativa' : `${total} ativas`),
  days: {
    monday: 'Segunda-feira',
    tuesday: 'Terça-feira',
    wednesday: 'Quarta-feira',
    thursday: 'Quinta-feira',
    friday: 'Sexta-feira',
    saturday: 'Sábado',
    sunday: 'Domingo',
  },
  week: {
    title: 'Horário semanal regular',
    description: 'Defina o horário de abertura e fechamento de cada dia. Os horários de reserva são gerados dentro desse intervalo.',
    timezone: 'Fuso horário: America/Bogota (COT)',
    working: 'Útil',
    rest: 'Descanso',
    opening: 'Abertura',
    closing: 'Fechamento',
    pause: 'Pausa',
    noPause: 'Contínuo (sem pausa)',
    notApplicable: 'Não se aplica',
    open: 'Aberto',
    closed: 'Fechado',
    info: 'As mudanças afetam o motor de reservas em tempo real.',
    reset: 'Restaurar valores',
    save: 'Salvar alterações',
    savedTitle: 'Horário salvo',
    savedMessage: 'As mudanças já se aplicam ao motor de reservas.',
    invalidTitle: 'Revise os horários',
    invalidMessage: 'Corrija os dias marcados em vermelho antes de salvar.',
    errors: {
      time: 'Use o formato hh:mm de 24 horas (ex. 18:30)',
      range: 'A abertura deve ser antes do fechamento',
      pause: 'A pausa deve estar dentro do horário de atendimento',
    },
  },
  exceptions: {
    title: 'Exceções e dias especiais',
    count: (total: number) => (total === 1 ? '1 programada' : `${total} programadas`),
    subtitle: 'Substitua o horário habitual em feriados nacionais, manutenções programadas ou jornadas reduzidas.',
    add: 'Adicionar exceção',
    empty: 'Não há exceções programadas',
    emptyHint: 'Adicione a primeira com o botão acima',
    closedAllDay: 'Fechado o dia todo',
    types: { holiday: 'Feriado nacional', special: 'Horário especial', maintenance: 'Manutenção' },
    deleteTitle: 'Excluir exceção',
    deleteMessage: (date: string) => `Tem certeza de que deseja excluir a exceção de ${date}? Esta ação não pode ser desfeita.`,
    form: {
      createTitle: 'Adicionar exceção',
      editTitle: 'Editar exceção',
      date: 'Data',
      datePlaceholder: 'dd/mm/aaaa',
      type: 'Tipo',
      closedAllDay: 'Fechado o dia todo',
      opening: 'Abertura',
      closing: 'Fechamento',
      description: 'Motivo / descrição',
      descriptionPlaceholder: 'Ex. Dia da Independência de Cartagena',
      save: 'Salvar exceção',
      errors: {
        date: 'Data inválida (dd/mm/aaaa)',
        duplicate: 'Já existe uma exceção nessa data',
        time: 'Hora inválida (hh:mm)',
        range: 'A abertura deve ser antes do fechamento',
      },
    },
    history: { added: 'Exceção adicionada', updated: 'Exceção atualizada', deleted: 'Exceção excluída' },
  },
  bays: {
    title: 'Baias de lavagem',
    subtitle: 'Ative, desative ou coloque em manutenção cada baia física do local.',
    add: 'Adicionar baia',
    currentOperator: (name: string) => `Operador atual: ${name}`,
    unassigned: 'Sem atribuição',
    state: 'Status',
    empty: 'Não há baias cadastradas',
    emptyHint: 'Adicione a primeira com o botão acima',
    status: { active: 'Ativa', maintenance: 'Em manutenção', inactive: 'Inativa' },
    deleteTitle: 'Excluir baia',
    deleteMessage: (name: string) => `Tem certeza de que deseja excluir ${name}? Esta ação não pode ser desfeita.`,
    form: {
      createTitle: 'Adicionar baia',
      editTitle: 'Editar baia',
      subtitle: 'Cadastre uma nova baia ou atualize seu status e operador.',
      name: 'Nome da baia',
      namePlaceholder: 'Ex. Baia 5',
      status: 'Status',
      operator: 'Operador atribuído',
      create: 'Criar',
      save: 'Salvar alterações',
      errors: { name: 'Informe o nome (mínimo 2 caracteres)', duplicate: 'Já existe uma baia com esse nome' },
    },
    history: { added: 'Baia adicionada', updated: 'Baia atualizada', statusChanged: 'Status da baia atualizado', deleted: 'Baia excluída' },
  },
  historyModal: {
    title: 'Histórico de alterações',
    subtitle: 'Últimas alterações no horário do negócio',
    empty: 'Ainda não há alterações registradas',
    weekUpdated: 'Horário semanal atualizado',
  },
};

export const SCHEDULE_TEXTS = localized({ es, en, fr, pt });
